import { beforeEach, describe, expect, it, vi } from "vitest";
import { isHttpError } from "@sveltejs/kit";
vi.mock(
  "$lib/server/data/store",
  () => import("$lib/server/data/store-memory"),
);
vi.mock("$lib/server/mail", () => ({
  sendAttendanceNotification: vi.fn(async () => {}),
}));
import { __reset } from "$lib/server/data/store-memory";
import {
  _resetDataLayerForTests,
  getTable,
  getQueue,
  mutate,
} from "$lib/server/data/tables";
import { invalidateCache } from "$lib/server/cache";
import { capabilitiesFor } from "$lib/server/core/capabilities";
import {
  EventSchema,
  StudySchema,
  MemberSchema,
} from "$lib/server/data/schemas";
import { toKstIso } from "$lib/server/core/time";
import { sendAttendanceNotification } from "$lib/server/mail";
import {
  load as memberLoad,
  actions as memberActions,
} from "./(member)/events/[id]/[type]/+page.server";
import {
  load as sheetLoad,
  actions as sheetActions,
} from "./(member)/study/[id]/attendance/+page.server";
const iso = (offset = 0) => toKstIso(new Date(Date.now() + offset));
const row = (id: string, legacy: string | null = null) =>
  MemberSchema.parse({
    id,
    name: `예시 ${id}`,
    department: "수리과학부",
    joinedAt: "2026-09-01",
    status: "regular",
    statusChangedAt: iso(),
    withdrawal: null,
    isAlumni: false,
    alumniRevoked: false,
    alumniRevocationReason: null,
    roles: [],
    isAdmin: false,
    publicContact: null,
    project: null,
    legacyMemberId: legacy,
    sourceRequestId: null,
  });
const study = (status = "ongoing", organizerId = "host") =>
  StudySchema.parse({
    id: "study",
    title: "예시 스터디",
    semester: "26-2",
    textbook: "",
    description: "",
    note: "",
    organizerIds: [organizerId],
    participantIds: ["host", "learner"],
    pendingParticipantIds: [],
    pendingTransfer: null,
    schedule: [],
    transferHistory: [],
    photos: [],
    status,
    sourceRequestId: null,
  });
const event = (id = "active", status = "active", start = iso(-3600000)) =>
  EventSchema.parse({
    id,
    title: "예시 스터디 회차",
    date: { start, end: iso(3600000) },
    type: "스터디",
    status,
    pathId: `PRIVATE_PATH_${id}`,
    attendCode: `PRIVATE_CODE_${id}`,
    activityId: `activity-${id}`,
    applicantIds: ["FORBIDDEN_APPLICANT_ID"],
    presenterIds: ["host"],
    studyId: "study",
    sessionNo: 1,
    autoGenerated: false,
    sourceRequestId: "PRIVATE_SOURCE_REQUEST",
  });
function locals(id = "learner", canWrite = true) {
  return {
    member: {
      memberId: id,
      name: `예시 ${id}`,
      status: "regular",
      isAdmin: false,
      isAlumni: !canWrite,
      registered: canWrite,
      capabilities: capabilitiesFor({
        isAlumni: !canWrite,
        registered: canWrite,
      }),
    },
    auth: async () => ({
      user: {
        name: `예시 ${id}`,
        email: `${id}@example.test`,
        image: "UNNEEDED_IMAGE",
      },
    }),
  } as unknown as App.Locals;
}
const memberEvent = (
  as = locals(),
  id = "active",
  code = `PRIVATE_CODE_${id}`,
) =>
  ({
    params: { id: `PRIVATE_PATH_${id}`, type: code },
    locals: as,
    url: new URL(`http://localhost/events/PRIVATE_PATH_${id}/${code}`),
  }) as unknown as Parameters<typeof memberLoad>[0];
const sheetEvent = (as = locals("host")) =>
  ({ params: { id: "study" }, locals: as }) as unknown as Parameters<
    typeof sheetLoad
  >[0];
async function save(id: string, selected: string[], as = locals("host")) {
  const form = new FormData();
  form.set("eventId", id);
  for (const who of selected) form.append("attendeeIds", who);
  return sheetActions.saveAttendance({
    params: { id: "study" },
    locals: as,
    request: new Request("http://localhost/", { method: "POST", body: form }),
  });
}
async function seed(events = [event()]) {
  await mutate("members", () => [row("host"), row("learner"), row("stranger")]);
  await mutate("studies", () => [study()]);
  await mutate("events", () => events);
  await mutate("activities", () =>
    events.map((e) => ({
      id: e.activityId,
      title: e.title,
      date: e.date,
      type: e.type,
      attendeeIds: ["host", "OUTSIDE_ROSTER"],
      sourceRequestId: e.sourceRequestId,
    })),
  );
}
beforeEach(async () => {
  __reset();
  _resetDataLayerForTests({ backoffBaseMs: 1 });
  vi.clearAllMocks();
  await invalidateCache("table_attendance-queue_active");
  for (const t of [
    "members",
    "studies",
    "events",
    "activities",
    "seminars",
    "legacy-members",
  ])
    await invalidateCache(`table_${t}`);
});

describe("member attendance route safe projection and guarded URL", () => {
  it("projects only actual metadata and own confirmation identity", async () => {
    await seed();
    const result = (await memberLoad(memberEvent())) as {
      event: object;
      context: object;
      user: object;
      canAttend: boolean;
    };
    expect(Object.keys(result.event).sort()).toEqual(["date", "title", "type"]);
    expect(Object.keys(result.user).sort()).toEqual(["email", "name"]);
    expect(result.canAttend).toBe(true);
    expect(result.context).toMatchObject({
      primaryLabel: "발표자",
      primaryValue: "예시 host",
      secondaryLabel: "회차",
      secondaryValue: "1회차",
    });
    expect(JSON.stringify(result)).not.toMatch(
      /PRIVATE_PATH|PRIVATE_CODE|PRIVATE_SOURCE|FORBIDDEN_APPLICANT|activity-active|UNNEEDED_IMAGE/,
    );
  });
  it("read-only member gets metadata but cannot be offered a request", async () => {
    await seed();
    expect(
      await memberLoad(memberEvent(locals("learner", false))),
    ).toMatchObject({ canAttend: false });
  });
  it.each(["draft", "expired"])(
    "correct %s link is 403, wrong code is concealed 404 first",
    async (status) => {
      await seed([event("active", status)]);
      await expect(memberLoad(memberEvent())).rejects.toSatisfy((e) =>
        isHttpError(e, 403),
      );
      await expect(
        memberLoad(memberEvent(locals(), "active", "wrong")),
      ).rejects.toSatisfy((e) => isHttpError(e, 404));
    },
  );
  it("cancelled event stays concealed", async () => {
    await seed([event("active", "cancelled")]);
    await expect(memberLoad(memberEvent())).rejects.toSatisfy((e) =>
      isHttpError(e, 404),
    );
  });
  it("action needs no event/body field and records the logged-in member only", async () => {
    await seed();
    const answer = await memberActions.attend(memberEvent() as never);
    expect(answer).toMatchObject({ success: true });
    expect(await getQueue("active")).toMatchObject([
      { memberId: "learner", status: "pending" },
    ]);
    expect((await getTable("activities"))[0].attendeeIds).not.toContain(
      "learner",
    );
    expect(sendAttendanceNotification).toHaveBeenCalledTimes(1);
  });
  it("duplicate request does not imply approval or duplicate notification", async () => {
    await seed();
    await memberActions.attend(memberEvent() as never);
    const answer = await memberActions.attend(memberEvent() as never);
    expect(answer).toMatchObject({ status: 409, data: { error: "CONFLICT" } });
    expect(await getQueue("active")).toHaveLength(1);
    expect(sendAttendanceNotification).toHaveBeenCalledTimes(1);
  });
  it("wrong action URL cannot create a queue row", async () => {
    await seed();
    expect(
      await memberActions.attend(
        memberEvent(locals(), "active", "wrong") as never,
      ),
    ).toMatchObject({ status: 404 });
    expect(await getQueue("active")).toHaveLength(0);
  });
  it("missing session is rejected before a queue write", async () => {
    await seed();
    const as = locals();
    as.auth = async () => null;
    expect(await memberActions.attend(memberEvent(as) as never)).toMatchObject({
      status: 401,
    });
    expect(await getQueue("active")).toHaveLength(0);
  });
});

describe("organizer attendance correction route", () => {
  it("cancelled sessions are omitted and expired sessions remain correctable", async () => {
    await seed([
      event(),
      event("old", "expired"),
      event("cancelled", "cancelled"),
    ]);
    const data = (await sheetLoad(sheetEvent())) as {
      sessions: { eventId: string }[];
      canSave: boolean;
    };
    expect(data.sessions.map((s) => s.eventId)).toEqual(["active", "old"]);
    expect(data.canSave).toBe(true);
    expect(await save("old", ["learner"])).toMatchObject({ success: true });
    expect(
      (await getTable("activities")).find((a) => a.id === "activity-old")
        ?.attendeeIds,
    ).toEqual(["OUTSIDE_ROSTER", "learner"]);
  });
  it.each(["finished", "cancelled"])(
    "%s study still permits correction",
    async (status) => {
      await seed();
      await mutate("studies", () => [study(status)]);
      expect(await save("active", ["learner"])).toMatchObject({
        success: true,
      });
    },
  );
  it("empty selection removes roster attendance and preserves outsiders", async () => {
    await seed();
    expect(await save("active", [])).toMatchObject({ success: true });
    expect((await getTable("activities"))[0].attendeeIds).toEqual([
      "OUTSIDE_ROSTER",
    ]);
  });
  it("forged attendee outside roster fails without changing activity", async () => {
    await seed();
    expect(await save("active", ["stranger"])).toMatchObject({ status: 400 });
    expect((await getTable("activities"))[0].attendeeIds).toEqual([
      "host",
      "OUTSIDE_ROSTER",
    ]);
  });
  it("forged cancelled event fails without changing activity", async () => {
    await seed([event("cancelled", "cancelled")]);
    expect(await save("cancelled", ["learner"])).toMatchObject({ status: 409 });
    expect((await getTable("activities"))[0].attendeeIds).toEqual([
      "host",
      "OUTSIDE_ROSTER",
    ]);
  });
  it("nonorganizer cannot read or save the sheet", async () => {
    await seed();
    await expect(sheetLoad(sheetEvent(locals("learner")))).rejects.toSatisfy(
      (e) => isHttpError(e, 403),
    );
    expect(await save("active", ["learner"], locals("learner"))).toMatchObject({
      status: 403,
    });
  });
  it("linked legacy organizer authority is preserved", async () => {
    await seed();
    await mutate("members", () => [row("host", "legacy-host"), row("learner")]);
    await mutate("studies", () => [study("ongoing", "legacy-host")]);
    expect(await sheetLoad(sheetEvent())).toMatchObject({ canSave: true });
    expect(await save("active", ["learner"])).toMatchObject({ success: true });
  });
  it("read-only organizer can view but gets canSave false", async () => {
    await seed();
    expect(await sheetLoad(sheetEvent(locals("host", false)))).toMatchObject({
      canSave: false,
    });
  });
});
