import { fail, type ActionFailure } from "@sveltejs/kit";
import type { z } from "zod/v4";
import { formText } from "$lib/domain/form-data";
import {
  studyFormIssues,
  studyParticipantInputSchema,
  studySessionCreateInputSchema,
  studySessionTargetInputSchema,
  studySessionUpdateInputSchema,
  studyStatusInputSchema,
  studyTransferInputSchema,
} from "$lib/domain/studies";
import { ensureOrganizer, handleUserAction } from "$lib/server/auth-guards";
import { httpGuard } from "$lib/server/core/http";
import { kstInputToIso, nowKstIso } from "$lib/server/core/time";
import { getTable } from "$lib/server/data/tables";
import { memberPickers } from "$lib/server/data/repos";
import { effectiveStatus } from "$lib/server/services/events";
import {
  acceptParticipant,
  cancelSession,
  cancelTransfer,
  createStudySession,
  proposeTransfer,
  removeParticipant,
  setStudyStatus,
  updateSession,
} from "$lib/server/services/studies";
import type { PageServerLoad } from "./$types";

/** STU-04·06·07: the organizer hub. Guard re-fetches the study every time. */
export const load: PageServerLoad = async ({ locals, params }) => {
  const study = await httpGuard(() =>
    ensureOrganizer(params.id, locals.member!.memberId),
  );

  const [events, activities, members] = await Promise.all([
    getTable("events"),
    getTable("activities"),
    memberPickers(),
  ]);
  const byId = new Map(members.map((m) => [m.id, m]));
  const attendeeCountOf = new Map(
    activities.map((a) => [a.id, a.attendeeIds.length]),
  );
  const resolve = (ids: string[]) =>
    ids.map((id) => ({
      id,
      name: byId.get(id)?.name ?? "Unknown",
      department: byId.get(id)?.department ?? "",
    }));

  return {
    study: {
      id: study.id,
      title: study.title,
      semester: study.semester,
      textbook: study.textbook,
      description: study.description,
      note: study.note,
      status: study.status,
      organizerIds: study.organizerIds,
      pendingTransfer: study.pendingTransfer
        ? {
            ...study.pendingTransfer,
            toName:
              byId.get(study.pendingTransfer.toMemberId)?.name ?? "Unknown",
            toDepartment:
              byId.get(study.pendingTransfer.toMemberId)?.department ?? "",
          }
        : null,
    },
    pendingParticipants: resolve(study.pendingParticipantIds),
    participants: resolve(study.participantIds),
    sessions: events
      .filter((e) => e.studyId === study.id)
      .sort((a, b) => (a.sessionNo ?? 0) - (b.sessionNo ?? 0))
      .map((e) => ({
        eventId: e.id,
        sessionNo: e.sessionNo,
        title: e.title,
        date: e.date.start,
        status: effectiveStatus(e),
        autoGenerated: e.autoGenerated,
        attendPath: `/events/${e.pathId}/${e.attendCode}`,
        attendanceCount: attendeeCountOf.get(e.activityId) ?? 0,
      })),
    members,
    generatedAt: nowKstIso(),
  };
};

type Ctx = { request: Request; locals: App.Locals; params: { id: string } };
type Failure = ActionFailure<Record<string, unknown>>;

/** The organizer guard runs first: a non-organizer never learns the rules. */
function organizerAction(
  logic: (data: FormData, ctx: Ctx) => Promise<void | Failure>,
): (ctx: Ctx) => Promise<unknown> {
  return async (ctx) => {
    const data = await ctx.request.formData();
    return handleUserAction(ctx.locals, async () => {
      await ensureOrganizer(ctx.params.id, ctx.locals.member!.memberId);
      return (await logic(data, ctx)) ?? {};
    });
  };
}

/**
 * Parses with a domain schema from $lib/domain/studies; on failure the
 * action answers 400 with every field issue and the values it read.
 */
function parse<T>(
  schema: z.ZodType<T>,
  values: Record<string, string>,
): { data: T; failure?: never } | { failure: Failure } {
  const parsed = schema.safeParse(values);
  if (parsed.success) return { data: parsed.data };
  return {
    failure: fail(400, {
      error: "VALIDATION_FAILED",
      issues: studyFormIssues(parsed.error),
      values,
    }),
  };
}

export const actions = {
  acceptParticipant: organizerAction(async (data, ctx) => {
    const input = parse(studyParticipantInputSchema, {
      memberId: formText(data, "memberId"),
    });
    if (input.failure) return input.failure;
    await acceptParticipant(ctx.params.id, input.data.memberId);
  }),

  removeParticipant: organizerAction(async (data, ctx) => {
    const input = parse(studyParticipantInputSchema, {
      memberId: formText(data, "memberId"),
    });
    if (input.failure) return input.failure;
    await removeParticipant(ctx.params.id, input.data.memberId);
  }),

  setStudyStatus: organizerAction(async (data, ctx) => {
    const input = parse(studyStatusInputSchema, {
      status: formText(data, "status"),
    });
    if (input.failure) return input.failure;
    await setStudyStatus(ctx.params.id, input.data.status);
  }),

  createSession: organizerAction(async (data, ctx) => {
    const input = parse(studySessionCreateInputSchema, {
      startedAtLocal: formText(data, "date"),
      title: formText(data, "title"),
    });
    if (input.failure) return input.failure;
    const study = await ensureOrganizer(
      ctx.params.id,
      ctx.locals.member!.memberId,
    );
    await createStudySession(study, kstInputToIso(input.data.startedAtLocal), {
      title: input.data.title || undefined,
      autoGenerated: false,
    });
  }),

  updateSession: organizerAction(async (data, ctx) => {
    const input = parse(studySessionUpdateInputSchema, {
      eventId: formText(data, "eventId"),
      title: formText(data, "title"),
      startedAtLocal: formText(data, "date"),
    });
    if (input.failure) return input.failure;
    await updateSession(ctx.params.id, input.data.eventId, {
      title: input.data.title,
      dateIso: kstInputToIso(input.data.startedAtLocal),
    });
  }),

  cancelSession: organizerAction(async (data, ctx) => {
    const input = parse(studySessionTargetInputSchema, {
      eventId: formText(data, "eventId"),
    });
    if (input.failure) return input.failure;
    await cancelSession(ctx.params.id, input.data.eventId);
  }),

  proposeTransfer: organizerAction(async (data, ctx) => {
    const input = parse(studyTransferInputSchema, {
      toMemberId: formText(data, "toMemberId"),
    });
    if (input.failure) return input.failure;
    await proposeTransfer(
      ctx.params.id,
      ctx.locals.member!.memberId,
      input.data.toMemberId,
    );
  }),

  cancelTransfer: organizerAction(async (_data, ctx) => {
    await cancelTransfer(ctx.params.id);
  }),
};
