<script lang="ts">
	import { enhance } from '$app/forms';
	import type { PageData } from './$types';

	let { data }: { data: PageData } = $props();
	const s = $derived(data.study);

	async function copyLink(path: string) {
		await navigator.clipboard.writeText(`${location.origin}${path}`);
	}
</script>

<svelte:head><title>{s.title} 관리 — SNUMPS</title></svelte:head>

<section class="manage">
	<h1>{s.title} — 스터디 관리</h1>

	<form method="POST" action="?/setStudyStatus" use:enhance>
		<h2>상태 ({s.status})</h2>
		<select name="status">
			{#each ['recruiting', 'ongoing', 'finished'] as st (st)}
				<option value={st} selected={st === s.status}>{st}</option>
			{/each}
		</select>
		<button>변경</button>
	</form>

	<section class="box">
		<h2>참여 신청 대기 ({data.pendingParticipants.length})</h2>
		{#each data.pendingParticipants as p (p.id)}
			<div class="row">
				{p.name} ({p.department})
				<form method="POST" action="?/acceptParticipant" use:enhance style="display:inline">
					<input type="hidden" name="memberId" value={p.id} /><button>수락</button>
				</form>
				<form method="POST" action="?/removeParticipant" use:enhance style="display:inline">
					<input type="hidden" name="memberId" value={p.id} /><button>거절</button>
				</form>
			</div>
		{/each}
	</section>

	<section class="box">
		<h2>참여자 ({data.participants.length})</h2>
		{#each data.participants as p (p.id)}
			<div class="row">
				{p.name} ({p.department})
				<form method="POST" action="?/removeParticipant" use:enhance style="display:inline">
					<input type="hidden" name="memberId" value={p.id} /><button>제외</button>
				</form>
			</div>
		{/each}
	</section>

	<section class="box">
		<h2>회차</h2>
		{#each data.sessions as sess (sess.eventId)}
			<div class="row">
				{sess.sessionNo}회차 — {new Date(sess.date).toLocaleString('ko-KR')} ({sess.status}{sess.autoGenerated ? ' · 자동' : ''})
				<button type="button" onclick={() => copyLink(sess.attendPath)}>출석 링크 복사</button>
				{#if sess.status !== 'cancelled'}
					<form method="POST" action="?/cancelSession" use:enhance style="display:inline">
						<input type="hidden" name="eventId" value={sess.eventId} /><button>취소</button>
					</form>
				{/if}
			</div>
		{/each}
		<form method="POST" action="?/createSession" use:enhance>
			<label>회차 추가 <input name="date" type="datetime-local" required /></label>
			<button>생성</button>
		</form>
		<form method="POST" action="?/registerSchedule" use:enhance>
			<label>일정 사전 등록 (한 줄에 하나, YYYY-MM-DDTHH:mm — 도래 시 자동 생성)
				<textarea name="dates" rows="3"></textarea>
			</label>
			<button>등록</button>
		</form>
	</section>

	<section class="box">
		<h2>주최자 전달</h2>
		{#if s.pendingTransfer}
			<p>{s.pendingTransfer.toName}님의 수락 대기 중</p>
			<form method="POST" action="?/cancelTransfer" use:enhance><button>철회</button></form>
		{:else}
			<form method="POST" action="?/proposeTransfer" use:enhance>
				<select name="toMemberId">
					{#each data.members as m (m.id)}<option value={m.id}>{m.name} ({m.department})</option>{/each}
				</select>
				<button>전달 제안</button>
				<p class="note">대상자가 대시보드에서 수락하면 완료됩니다.</p>
			</form>
		{/if}
	</section>
</section>

<style>
	.manage { max-width: 38rem; margin: 2rem auto; padding: 0 1rem; display: flex; flex-direction: column; gap: 1rem; }
	.box { border: 1px solid #8886; padding: 0.9rem; display: flex; flex-direction: column; gap: 0.5rem; }
	.row { display: flex; gap: 0.5rem; align-items: center; flex-wrap: wrap; }
	form { display: flex; flex-direction: column; gap: 0.4rem; }
	button { padding: 0.25rem 0.8rem; cursor: pointer; align-self: flex-start; }
	.note { font-size: 0.85rem; opacity: 0.7; margin: 0; }
</style>
