import { ensureOrganizer, handleUserAction } from "$lib/server/auth-guards";
import { AppError } from "$lib/server/core/errors";
import { kstInputToIso } from "$lib/server/core/time";
import { getTable } from "$lib/server/data/tables";
import { memberPickers } from "$lib/server/data/repos";
import { effectiveStatus } from "$lib/server/services/events";
import {
  acceptParticipant,
  cancelSession,
  cancelTransfer,
  createStudySession,
  proposeTransfer,
  registerSchedule,
  removeParticipant,
  setStudyStatus,
  updateSession,
} from "$lib/server/services/studies";
import { StudyStatus } from "$lib/server/data/schemas";
import type { PageServerLoad } from "./$types";

/** STU-04·06·07: the organizer hub. Guard re-fetches the study every time. */
export const load: PageServerLoad = async ({ locals, params }) => {
  const study = await ensureOrganizer(params.id, locals.member!.memberId);

  const [events, members] = await Promise.all([getTable("events"), memberPickers()]);
  const byId = new Map(members.map((m) => [m.id, m]));
  const resolve = (ids: string[]) =>
    ids.map((id) => ({
      id,
      name: byId.get(id)?.name ?? "Unknown",
      department: byId.get(id)?.department ?? "",
    }));

  return {
    study: {
      id: study.id,
      title: study.title,
      status: study.status,
      schedule: study.schedule,
      pendingTransfer: study.pendingTransfer
        ? {
            ...study.pendingTransfer,
            toName: byId.get(study.pendingTransfer.toMemberId)?.name ?? "Unknown",
          }
        : null,
    },
    pendingParticipants: resolve(study.pendingParticipantIds),
    participants: resolve(study.participantIds),
    sessions: events
      .filter((e) => e.studyId === study.id)
      .sort((a, b) => (a.sessionNo ?? 0) - (b.sessionNo ?? 0))
      .map((e) => ({
        eventId: e.id,
        sessionNo: e.sessionNo,
        title: e.title,
        date: e.date.start,
        status: effectiveStatus(e),
        autoGenerated: e.autoGenerated,
        attendPath: `/events/${e.pathId}/${e.attendCode}`,
      })),
    members,
  };
};

type Ctx = { request: Request; locals: App.Locals; params: { id: string } };

function organizerAction(
  logic: (data: FormData, ctx: Ctx) => Promise<void>,
): (ctx: Ctx) => Promise<unknown> {
  return async (ctx) => {
    const data = await ctx.request.formData();
    return handleUserAction(ctx.locals, async () => {
      await ensureOrganizer(ctx.params.id, ctx.locals.member!.memberId);
      await logic(data, ctx);
      return {};
    });
  };
}

export const actions = {
  acceptParticipant: organizerAction(async (data, ctx) => {
    await acceptParticipant(ctx.params.id, data.get("memberId") as string);
  }),

  removeParticipant: organizerAction(async (data, ctx) => {
    await removeParticipant(ctx.params.id, data.get("memberId") as string);
  }),

  setStudyStatus: organizerAction(async (data, ctx) => {
    await setStudyStatus(ctx.params.id, StudyStatus.parse(data.get("status")));
  }),

  createSession: organizerAction(async (data, ctx) => {
    const dateRaw = data.get("date") as string;
    if (!dateRaw) throw new AppError("VALIDATION_FAILED");
    const study = await ensureOrganizer(ctx.params.id, ctx.locals.member!.memberId);
    await createStudySession(study, kstInputToIso(dateRaw), {
      title: (data.get("title") as string)?.trim() || undefined,
      autoGenerated: false,
    });
  }),

  registerSchedule: organizerAction(async (data, ctx) => {
    // one datetime-local per line
    const dates = ((data.get("dates") as string) ?? "")
      .split("\n")
      .map((s) => s.trim())
      .filter(Boolean)
      .map(kstInputToIso);
    await registerSchedule(ctx.params.id, dates);
  }),

  updateSession: organizerAction(async (data, ctx) => {
    const dateRaw = data.get("date") as string;
    await updateSession(ctx.params.id, data.get("eventId") as string, {
      title: (data.get("title") as string)?.trim() || undefined,
      dateIso: dateRaw ? kstInputToIso(dateRaw) : undefined,
    });
  }),

  cancelSession: organizerAction(async (data, ctx) => {
    await cancelSession(ctx.params.id, data.get("eventId") as string);
  }),

  proposeTransfer: organizerAction(async (data, ctx) => {
    await proposeTransfer(
      ctx.params.id,
      ctx.locals.member!.memberId,
      data.get("toMemberId") as string,
    );
  }),

  cancelTransfer: organizerAction(async (_data, ctx) => {
    await cancelTransfer(ctx.params.id);
  }),
};
