import { beforeEach, describe, expect, it, vi } from "vitest";

vi.mock(
  "$lib/server/data/store",
  () => import("$lib/server/data/store-memory"),
);

import { __reset } from "$lib/server/data/store-memory";
import { _resetDataLayerForTests, mutate } from "$lib/server/data/tables";
import { invalidateCache } from "$lib/server/cache";
import { nowKstIso } from "$lib/server/core/time";
import { load } from "./+page.server";

/**
 * sessionCount gates the editor's delete button (deleteStudy refuses while
 * sessions exist). It counted pre-registered schedule entries — none exist
 * in practice — so a study with real sessions showed 0 and offered a delete
 * that then failed. It counts the study's session events now.
 */

const admin = {
  member: {
    memberId: "admin",
    privateInfoId: null,
    name: "관리자",
    status: "regular",
    isAdmin: true,
    isAlumni: false,
    registered: true,
    capabilities: [],
  },
  auth: async () => ({ user: { email: "admin@snu.ac.kr", name: "관리자" } }),
} as unknown as App.Locals;

const session = (id: string, studyId: string | null) => ({
  id,
  title: "1회차",
  date: { start: nowKstIso(), end: null },
  type: "스터디" as const,
  status: "active" as const,
  pathId: id,
  attendCode: id,
  activityId: `a-${id}`,
  applicantIds: [],
  presenterIds: [],
  studyId,
  sessionNo: 1,
  autoGenerated: false,
  sourceRequestId: null,
});

beforeEach(async () => {
  __reset();
  _resetDataLayerForTests({ backoffBaseMs: 1 });
  for (const t of ["studies", "events", "members", "study-requests"]) {
    await invalidateCache(`table_${t}`);
  }
});

describe("admin study records", () => {
  it("count the study's real sessions", async () => {
    await mutate("studies", () => [
      {
        id: "st1",
        title: "해석학",
        semester: "26-2",
        textbook: "",
        description: "",
        note: "",
        organizerIds: ["m1"],
        participantIds: ["m1"],
        pendingParticipantIds: [],
        pendingTransfer: null,
        schedule: [],
        transferHistory: [],
        photos: [],
        status: "ongoing" as const,
        sourceRequestId: null,
      },
    ]);
    await mutate("events", () => [
      session("e1", "st1"),
      session("e2", "st1"),
      session("e3", null),
    ]);

    const data = (await load({ locals: admin } as never)) as {
      records: { id: string; sessionCount: number }[];
    };

    expect(data.records.find((r) => r.id === "st1")?.sessionCount).toBe(2);
  });
});
