import { beforeEach, describe, expect, it, vi } from "vitest";

vi.mock(
  "$lib/server/data/store",
  () => import("$lib/server/data/store-memory"),
);

import { __reset } from "$lib/server/data/store-memory";
import { _resetDataLayerForTests, mutate } from "$lib/server/data/tables";
import { invalidateCache } from "$lib/server/cache";
import { newId } from "$lib/server/core/id";
import { toKstIso } from "$lib/server/core/time";
import type { Event, Seminar, Study } from "$lib/server/data/schemas";
import { getPublicActivities } from "$lib/server/public/archive";
import { cancelSession, createStudySession } from "./studies";
import { hiddenActivityIdsOf, withoutHiddenActivities } from "./visibility";
import { getTable } from "$lib/server/data/tables";

/**
 * Cancelling a study session cancelled its event and left its activity, so a
 * session that never happened still showed in the public calendar, the
 * dashboard counts and members' histories (audit LB31-1; the spec says the
 * activity goes with the session, FRONTEND-DECISIONS §3). The hiding rule
 * also lived twice — here and in the archive layout (LB21-1).
 */

beforeEach(async () => {
  await __reset();
  _resetDataLayerForTests({ backoffBaseMs: 1 });
  for (const t of ["activities", "events", "studies", "seminars"])
    await invalidateCache(`table_${t}`);
});

async function seedStudy(): Promise<Study> {
  const s: Study = {
    id: newId(),
    title: "해석학",
    semester: "26-2",
    textbook: "",
    description: "",
    note: "",
    organizerIds: ["org"],
    participantIds: ["org"],
    pendingParticipantIds: [],
    pendingTransfer: null,
    schedule: [],
    transferHistory: [],
    photos: [],
    status: "recruiting",
    sourceRequestId: null,
  };
  await mutate("studies", (rows) => [...rows, s]);
  return s;
}

describe("a cancelled study session", () => {
  it("takes its activity out of every member and guest view", async () => {
    const s = await seedStudy();
    const kept = await createStudySession(
      s,
      toKstIso(new Date(Date.now() + 3_600_000)),
      { autoGenerated: false },
    );
    const dropped = await createStudySession(
      s,
      toKstIso(new Date(Date.now() + 7_200_000)),
      { autoGenerated: false },
    );

    await cancelSession(s.id, dropped.id);

    const visible = (
      await withoutHiddenActivities(await getTable("activities"))
    ).map((a) => a.id);
    expect(visible).toEqual([kept.activityId]);
    expect(await getPublicActivities()).toHaveLength(1);
  });
});

describe("hiddenActivityIdsOf", () => {
  const event = (over: Partial<Event>): Event =>
    ({ id: "e", activityId: "a", status: "active", ...over }) as Event;
  const seminar = (over: Partial<Seminar>): Seminar =>
    ({
      id: "s",
      activityId: "a",
      publicationStatus: "published",
      ...over,
    }) as Seminar;

  it("hides the activity of an unpublished seminar", () => {
    expect([
      ...hiddenActivityIdsOf([seminar({ publicationStatus: "cancelled" })], []),
    ]).toEqual(["a"]);
  });

  it("hides an activity whose every event is cancelled, not one with a live event", () => {
    expect([
      ...hiddenActivityIdsOf(
        [],
        [
          event({ status: "cancelled" }),
          event({ id: "e2", status: "cancelled" }),
        ],
      ),
    ]).toEqual(["a"]);
    expect([
      ...hiddenActivityIdsOf(
        [],
        [
          event({ status: "cancelled" }),
          event({ id: "e2", status: "expired" }),
        ],
      ),
    ]).toEqual([]);
  });

  it("leaves an activity with no events alone", () => {
    expect([...hiddenActivityIdsOf([seminar({})], [])]).toEqual([]);
  });
});
