import { AppError, definedOnly } from "$lib/server/core/errors";
import { newId, randomToken } from "$lib/server/core/id";
import { endOfKstDay, nowKstIso } from "$lib/server/core/time";
import {
  getTable,
  listPendingQueues,
  mutate,
  mutateQueue,
} from "$lib/server/data/tables";
import { callFlow, type FlowResult } from "$lib/server/data/flows";
import { getDirectoryIndex } from "$lib/server/data/directory";
import { getMemberVisibleEvents } from "./visibility";
import type {
  Activity,
  AttendanceRecord,
  Event,
} from "$lib/server/data/schemas";
import { mergeAttendees } from "$lib/server/attendance";

/**
 * Event lifecycle + attendance queue (API-SPEC §5-4, §7-2, §8-1).
 * Status truth is LAZY: gates check effectiveStatus(), never the stored
 * value — the cron's expire pass is display hygiene, not enforcement.
 */

export function expiryOf(event: Event): Date {
  return event.date.end
    ? new Date(event.date.end)
    : endOfKstDay(event.date.start);
}

export function effectiveStatus(
  event: Event,
  now = new Date(),
): Event["status"] {
  if (event.status === "active" && expiryOf(event) < now) return "expired";
  return event.status;
}

/**
 * "This member presents this event" — the single owner of that rule (PRES-03).
 * Both the managed-seminar list and the nav's presenter flag go through it, so
 * widening the definition (a second seminar type, external presenters) is one
 * edit rather than two.
 */
export function presentsEvent(event: Event, memberId: string): boolean {
  return isSeminarType(event.type) && event.presenterIds.includes(memberId);
}

/**
 * PRES-03: does this member present anything at all?
 *
 * The invariant is that the nav link is visible exactly when
 * `getManagedSeminars` has rows, so both use `presentsEvent` and nothing else.
 * Do NOT add a status filter here: attendance is recorded AFTER the seminar —
 * `savePresenterAttendance` has no status gate on purpose — so filtering to
 * `active` would remove the link at midnight on the very night the presenter
 * needs it, while the page it points at still lists the seminar.
 */
export async function hasPresenterEvents(memberId: string): Promise<boolean> {
  // 취소된 세미나는 회원에게 존재하지 않는다 — 네비 플래그도 마찬가지다.
  const events = await getMemberVisibleEvents();
  return events.some((e) => presentsEvent(e, memberId));
}

// ---- creation ---------------------------------------------------------------

export async function createEventWithActivity(input: {
  title: string;
  startIso: string;
  type: Activity["type"];
  status?: Event["status"];
  presenterIds?: string[];
  attendeeIds?: string[];
  sourceRequestId?: string;
}): Promise<Event> {
  const activity: Activity = {
    id: newId(),
    title: input.title,
    date: { start: input.startIso, end: null },
    type: input.type,
    attendeeIds: input.attendeeIds ?? [],
    sourceRequestId: input.sourceRequestId ?? null,
  };
  await mutate("activities", (rows) => [...rows, activity]);
  return createSessionForActivity(activity, input);
}

/** ADM-05: attach a new attendance session to an existing activity (fields copied). */
export async function connectActivity(activityId: string): Promise<Event> {
  const activity = (await getTable("activities")).find(
    (a) => a.id === activityId,
  );
  if (!activity) throw new AppError("NOT_FOUND");
  return createSessionForActivity(activity, { status: "active" });
}

async function createSessionForActivity(
  activity: Activity,
  opts: {
    status?: Event["status"];
    presenterIds?: string[];
    sourceRequestId?: string;
  },
): Promise<Event> {
  const event: Event = {
    id: newId(),
    title: activity.title,
    date: activity.date,
    type: activity.type,
    status: opts.status ?? "draft",
    pathId: randomToken(),
    attendCode: randomToken(),
    activityId: activity.id,
    applicantIds: [],
    presenterIds: opts.presenterIds ?? [],
    studyId: null,
    sessionNo: null,
    autoGenerated: false,
    sourceRequestId: opts.sourceRequestId ?? null,
  };
  await mutate("events", (rows) => [...rows, event]);
  return event;
}

// ---- lifecycle --------------------------------------------------------------

/**
 * Opening cannot outrun the clock: once an event's end has passed,
 * effectiveStatus says "expired" whatever is stored, so writing "active"
 * would report success and change nothing (audit LB20-1). Refused instead —
 * the date has to be corrected first.
 */
export async function setEventStatus(
  id: string,
  status: "active" | "expired",
): Promise<void> {
  await mutate("events", (rows) => {
    const idx = rows.findIndex((e) => e.id === id);
    if (idx === -1) throw new AppError("NOT_FOUND");
    if (rows[idx].status === "cancelled") throw new AppError("CONFLICT"); // terminal
    if (status === "active" && expiryOf(rows[idx]) < new Date()) {
      throw new AppError("CONFLICT", {
        userMessage:
          "종료 시각이 지난 이벤트는 열 수 없습니다. 날짜를 먼저 수정해 주세요.",
      });
    }
    rows[idx] = { ...rows[idx], status };
    return rows;
  });
}

/**
 * §7-2: refuses while check-ins are still pending; removes the queue with the
 * event — one transaction (flow_delete_event), so a check-in cannot land
 * between the pending test and the delete.
 */
export async function deleteEventChecked(id: string): Promise<void> {
  await callFlow("flow_delete_event", { id });
}

// ---- check-in (EVT-01 / SEM-05 / STU-03) ------------------------------------

/**
 * A pending check-in. The caller found `event` through the member-visible
 * read (hidden seminars 404 there); flow_check_in re-reads it under a lock and
 * decides "still there and open" on that — the cached copy may be up to 15s
 * old, and a delete or cancel may have committed since.
 */
export async function checkIn(
  event: Event,
  memberId: string,
): Promise<AttendanceRecord> {
  if (effectiveStatus(event) !== "active") throw new AppError("EVENT_NOT_OPEN");
  const { record } = await callFlow<FlowResult & { record: AttendanceRecord }>(
    "flow_check_in",
    { eventId: event.id, memberId, id: newId(), now: nowKstIso() },
  );
  return record;
}

// ---- participation (EVT-02 / BE-43) -----------------------------------------

const SEMINAR_TYPES: readonly Event["type"][] = ["세미나"];

export function isSeminarType(type: Event["type"]): boolean {
  return SEMINAR_TYPES.includes(type);
}

function assertOpenForApplication(event: Event, now = new Date()): void {
  if (effectiveStatus(event, now) !== "active")
    throw new AppError("EVENT_NOT_OPEN");
  if (new Date(event.date.start) <= now) throw new AppError("EVENT_NOT_OPEN");
}

export async function applyToEvent(
  eventId: string,
  memberId: string,
): Promise<void> {
  await mutate("events", (rows) => {
    const idx = rows.findIndex((e) => e.id === eventId);
    if (idx === -1) throw new AppError("NOT_FOUND");
    assertOpenForApplication(rows[idx]);
    if (rows[idx].applicantIds.includes(memberId)) return rows; // idempotent no-op
    rows[idx] = {
      ...rows[idx],
      applicantIds: [...rows[idx].applicantIds, memberId],
    };
    return rows;
  });
}

export async function cancelEventApplication(
  eventId: string,
  memberId: string,
): Promise<void> {
  await mutate("events", (rows) => {
    const idx = rows.findIndex((e) => e.id === eventId);
    if (idx === -1) throw new AppError("NOT_FOUND");
    assertOpenForApplication(rows[idx]);
    rows[idx] = {
      ...rows[idx],
      applicantIds: rows[idx].applicantIds.filter((id) => id !== memberId),
    };
    return rows;
  });
}

// ---- presenter attendance management (PRES-01~04 / BE-44) -------------------

/** Seminars the member presents, with resolved applicants and current checks. */
export async function getManagedSeminars(memberId: string) {
  const [events, activities, memberById] = await Promise.all([
    // 취소된 세미나는 목록에서 사라진다 — 네비 플래그(hasPresenterEvents)와
    // 같은 집합을 봐야 "링크는 있는데 페이지는 비었다"가 생기지 않는다.
    getMemberVisibleEvents(),
    getTable("activities"),
    getDirectoryIndex(), // 표시용 이름·학과 — 과거 기록의 legacy id도 해석
  ]);
  const activityById = new Map(activities.map((a) => [a.id, a]));

  return events
    .filter((e) => presentsEvent(e, memberId))
    .sort((a, b) => a.date.start.localeCompare(b.date.start))
    .map((e) => {
      const attendees = activityById.get(e.activityId)?.attendeeIds ?? [];
      return {
        id: e.id,
        title: e.title,
        date: e.date.start,
        status: effectiveStatus(e),
        attendPath: `/events/${e.pathId}/${e.attendCode}`, // PRES-04 share link
        applicants: e.applicantIds.map((id) => ({
          id,
          name: memberById.get(id)?.name ?? "Unknown",
          department: memberById.get(id)?.department ?? "",
          checked: attendees.includes(id),
        })),
      };
    });
}

/**
 * BE-44 save: merge rule via mergeAttendees — attendees who arrived through
 * check-in (outside the applicant pool) always survive; selections outside
 * the pool are refused. Presenter authority is re-verified against the event.
 */
export async function savePresenterAttendance(
  eventId: string,
  presenterId: string,
  selectedApplicantIds: string[],
): Promise<void> {
  // 발표자 저장도 회원 면의 단일 통로를 탄다 — 취소된 세미나에는 기록을 남길 수 없다.
  const event = (await getMemberVisibleEvents()).find((e) => e.id === eventId);
  if (!event) throw new AppError("NOT_FOUND");
  if (!event.presenterIds.includes(presenterId))
    throw new AppError("FORBIDDEN");
  if (!isSeminarType(event.type)) throw new AppError("VALIDATION_FAILED");

  await mutate("activities", (rows) => {
    const idx = rows.findIndex((a) => a.id === event.activityId);
    if (idx === -1) throw new AppError("NOT_FOUND");
    const next = mergeAttendees(
      rows[idx].attendeeIds,
      event.applicantIds,
      selectedApplicantIds,
    );
    rows[idx] = { ...rows[idx], attendeeIds: next };
    return rows;
  });
}

// ---- queue administration (ADM-03) ------------------------------------------

/**
 * Approve credits the member on the event's activity; reject or delete of an
 * APPROVED row takes the credit back (§7-2). The queue row and the activity
 * change in one transaction (flow_decide_attendance) — decided on the row as
 * it is then, not as a page load showed it.
 */
async function decideAttendance(
  eventId: string,
  queueId: string,
  decision: "approve" | "reject" | "delete",
): Promise<void> {
  await callFlow("flow_decide_attendance", { eventId, queueId, decision });
}

export async function approveAttendance(
  eventId: string,
  queueId: string,
): Promise<void> {
  await decideAttendance(eventId, queueId, "approve");
}

export async function rejectAttendance(
  eventId: string,
  queueId: string,
): Promise<void> {
  await decideAttendance(eventId, queueId, "reject");
}

export async function deleteAttendanceRecord(
  eventId: string,
  queueId: string,
): Promise<void> {
  await decideAttendance(eventId, queueId, "delete");
}

export async function updateAttendanceTime(
  eventId: string,
  queueId: string,
  patch: { startTime?: string; endTime?: string },
): Promise<void> {
  await mutateQueue(eventId, (rows) => {
    const idx = rows.findIndex((r) => r.id === queueId);
    if (idx === -1) throw new AppError("NOT_FOUND");
    rows[idx] = { ...rows[idx], ...definedOnly(patch) };
    return rows;
  });
}

/** Admin dashboard: pending rows across all events, member names resolved. */
export async function getPendingAttendance() {
  const [queues, memberById, events] = await Promise.all([
    listPendingQueues(),
    getDirectoryIndex(), // 표시용 이름·학과만 — 큐 행 자체는 운영 데이터
    getTable("events"),
  ]);
  const eventById = new Map(events.map((e) => [e.id, e]));
  return queues.flatMap(({ eventId, rows }) =>
    rows.map((r) => ({
      ...r,
      userName: memberById.get(r.memberId)?.name ?? "Unknown",
      userDept: memberById.get(r.memberId)?.department ?? "",
      eventTitle: eventById.get(eventId)?.title ?? "(삭제된 이벤트)",
    })),
  );
}

// ---- cron (BE-35: skeleton + expire; later tasks register their own steps) --

export type CronStep = {
  name: string;
  run: () => Promise<Record<string, number>>;
};

const cronSteps: CronStep[] = [
  {
    name: "expire",
    run: async () => {
      const now = new Date();
      // Count candidates BEFORE the mutation — counting inside the fn would
      // double on conditional-write retries (review low-11).
      const expired = (await getTable("events")).filter(
        (e) => e.status === "active" && expiryOf(e) < now,
      ).length;
      await mutate("events", (rows) =>
        rows.map((e) =>
          e.status === "active" && expiryOf(e) < now
            ? { ...e, status: "expired" as const }
            : e,
        ),
      );
      return { expired };
    },
  },
];

export async function runCron(): Promise<Record<string, number>> {
  const results: Record<string, number> = {};
  for (const step of cronSteps) {
    try {
      Object.assign(results, await step.run());
    } catch (e) {
      console.error(`[Cron] step '${step.name}' failed:`, e);
      results[`${step.name}_failed`] = 1;
    }
  }
  // The route cannot tell a partial failure from a total one without knowing how
  // many steps there were — an empty registry and an all-green run look alike.
  results.steps_total = cronSteps.length;
  return results;
}
