import { AppError, definedOnly } from "$lib/server/core/errors";
import { newId, randomToken } from "$lib/server/core/id";
import { endOfKstDay, nowKstIso } from "$lib/server/core/time";
import {
  deleteQueue,
  getQueue,
  getTable,
  listPendingQueues,
  mutate,
  mutateQueue,
} from "$lib/server/data/tables";
import { getDirectoryIndex } from "$lib/server/data/directory";
import type { Activity, AttendanceRecord, Event } from "$lib/server/data/schemas";
import { invalidateAttendanceCaches, mergeAttendees } from "$lib/server/attendance";

/**
 * Event lifecycle + attendance queue (API-SPEC §5-4, §7-2, §8-1).
 * Status truth is LAZY: gates check effectiveStatus(), never the stored
 * value — the cron's expire pass is display hygiene, not enforcement.
 */

export function expiryOf(event: Event): Date {
  return event.date.end ? new Date(event.date.end) : endOfKstDay(event.date.start);
}

export function effectiveStatus(event: Event, now = new Date()): Event["status"] {
  if (event.status === "active" && expiryOf(event) < now) return "expired";
  return event.status;
}

export async function getEventByPath(
  pathId: string,
  attendCode: string,
): Promise<Event | null> {
  const events = await getTable("events");
  return (
    events.find((e) => e.pathId === pathId && e.attendCode === attendCode) ?? null
  );
}

// ---- creation ---------------------------------------------------------------

export async function createEventWithActivity(input: {
  title: string;
  startIso: string;
  type: Activity["type"];
  status?: Event["status"];
  presenterIds?: string[];
  attendeeIds?: string[];
  sourceRequestId?: string;
}): Promise<Event> {
  const activity: Activity = {
    id: newId(),
    title: input.title,
    date: { start: input.startIso, end: null },
    type: input.type,
    attendeeIds: input.attendeeIds ?? [],
    sourceRequestId: input.sourceRequestId ?? null,
  };
  await mutate("activities", (rows) => [...rows, activity]);
  return createSessionForActivity(activity, input);
}

/** ADM-05: attach a new attendance session to an existing activity (fields copied). */
export async function connectActivity(activityId: string): Promise<Event> {
  const activity = (await getTable("activities")).find((a) => a.id === activityId);
  if (!activity) throw new AppError("NOT_FOUND");
  return createSessionForActivity(activity, { status: "active" });
}

async function createSessionForActivity(
  activity: Activity,
  opts: {
    status?: Event["status"];
    presenterIds?: string[];
    sourceRequestId?: string;
  },
): Promise<Event> {
  const event: Event = {
    id: newId(),
    title: activity.title,
    date: activity.date,
    type: activity.type,
    status: opts.status ?? "draft",
    pathId: randomToken(),
    attendCode: randomToken(),
    activityId: activity.id,
    applicantIds: [],
    presenterIds: opts.presenterIds ?? [],
    studyId: null,
    sessionNo: null,
    autoGenerated: false,
    sourceRequestId: opts.sourceRequestId ?? null,
  };
  await mutate("events", (rows) => [...rows, event]);
  return event;
}

// ---- lifecycle --------------------------------------------------------------

export async function setEventStatus(
  id: string,
  status: "active" | "expired",
): Promise<void> {
  await mutate("events", (rows) => {
    const idx = rows.findIndex((e) => e.id === id);
    if (idx === -1) throw new AppError("NOT_FOUND");
    if (rows[idx].status === "cancelled") throw new AppError("CONFLICT"); // terminal
    rows[idx] = { ...rows[idx], status };
    return rows;
  });
}

/** §7-2: refuses while check-ins are still pending; removes the queue with the event. */
export async function deleteEventChecked(id: string): Promise<void> {
  const pending = (await getQueue(id)).some((r) => r.status === "pending");
  if (pending) throw new AppError("CONFLICT");
  await mutate("events", (rows) => {
    if (!rows.some((e) => e.id === id)) throw new AppError("NOT_FOUND");
    return rows.filter((e) => e.id !== id);
  });
  await deleteQueue(id);
}

// ---- check-in (EVT-01 / SEM-05 / STU-03) ------------------------------------

export async function checkIn(event: Event, memberId: string): Promise<AttendanceRecord> {
  if (effectiveStatus(event) !== "active") throw new AppError("EVENT_NOT_OPEN");
  const now = nowKstIso();
  let created: AttendanceRecord | undefined;
  await mutateQueue(event.id, (rows) => {
    if (rows.some((r) => r.memberId === memberId)) throw new AppError("CONFLICT");
    created = {
      id: newId(),
      memberId,
      eventId: event.id,
      startTime: now,
      endTime: now, // one-click completion records both instants
      status: "pending",
    };
    return [...rows, created];
  });
  return created!;
}

// ---- participation (EVT-02 / BE-43) -----------------------------------------

const SEMINAR_TYPES: readonly Event["type"][] = ["세미나"];

export function isSeminarType(type: Event["type"]): boolean {
  return SEMINAR_TYPES.includes(type);
}

function assertOpenForApplication(event: Event, now = new Date()): void {
  if (effectiveStatus(event, now) !== "active") throw new AppError("EVENT_NOT_OPEN");
  if (new Date(event.date.start) <= now) throw new AppError("EVENT_NOT_OPEN");
}

export async function applyToEvent(eventId: string, memberId: string): Promise<void> {
  await mutate("events", (rows) => {
    const idx = rows.findIndex((e) => e.id === eventId);
    if (idx === -1) throw new AppError("NOT_FOUND");
    assertOpenForApplication(rows[idx]);
    if (rows[idx].applicantIds.includes(memberId)) return rows; // idempotent no-op
    rows[idx] = { ...rows[idx], applicantIds: [...rows[idx].applicantIds, memberId] };
    return rows;
  });
}

export async function cancelEventApplication(
  eventId: string,
  memberId: string,
): Promise<void> {
  await mutate("events", (rows) => {
    const idx = rows.findIndex((e) => e.id === eventId);
    if (idx === -1) throw new AppError("NOT_FOUND");
    assertOpenForApplication(rows[idx]);
    rows[idx] = {
      ...rows[idx],
      applicantIds: rows[idx].applicantIds.filter((id) => id !== memberId),
    };
    return rows;
  });
}

// ---- presenter attendance management (PRES-01~04 / BE-44) -------------------

/** Seminars the member presents, with resolved applicants and current checks. */
export async function getManagedSeminars(memberId: string) {
  const [events, activities, memberById] = await Promise.all([
    getTable("events"),
    getTable("activities"),
    getDirectoryIndex(), // 표시용 이름·학과 — 과거 기록의 legacy id도 해석
  ]);
  const activityById = new Map(activities.map((a) => [a.id, a]));

  return events
    .filter((e) => isSeminarType(e.type) && e.presenterIds.includes(memberId))
    .sort((a, b) => a.date.start.localeCompare(b.date.start))
    .map((e) => {
      const attendees = activityById.get(e.activityId)?.attendeeIds ?? [];
      return {
        id: e.id,
        title: e.title,
        date: e.date.start,
        status: effectiveStatus(e),
        attendPath: `/events/${e.pathId}/${e.attendCode}`, // PRES-04 share link
        applicants: e.applicantIds.map((id) => ({
          id,
          name: memberById.get(id)?.name ?? "Unknown",
          department: memberById.get(id)?.department ?? "",
          checked: attendees.includes(id),
        })),
      };
    });
}

/**
 * BE-44 save: merge rule via mergeAttendees — attendees who arrived through
 * check-in (outside the applicant pool) always survive; selections outside
 * the pool are refused. Presenter authority is re-verified against the event.
 */
export async function savePresenterAttendance(
  eventId: string,
  presenterId: string,
  selectedApplicantIds: string[],
): Promise<void> {
  const event = (await getTable("events")).find((e) => e.id === eventId);
  if (!event) throw new AppError("NOT_FOUND");
  if (!event.presenterIds.includes(presenterId)) throw new AppError("FORBIDDEN");
  if (!isSeminarType(event.type)) throw new AppError("VALIDATION_FAILED");

  let touched: string[] = [];
  await mutate("activities", (rows) => {
    const idx = rows.findIndex((a) => a.id === event.activityId);
    if (idx === -1) throw new AppError("NOT_FOUND");
    const next = mergeAttendees(
      rows[idx].attendeeIds,
      event.applicantIds,
      selectedApplicantIds,
    );
    touched = [...new Set([...rows[idx].attendeeIds, ...next])];
    rows[idx] = { ...rows[idx], attendeeIds: next };
    return rows;
  });
  await invalidateAttendanceCaches(touched);
}

// ---- queue administration (ADM-03) ------------------------------------------

async function findQueueRow(eventId: string, queueId: string): Promise<AttendanceRecord> {
  const row = (await getQueue(eventId)).find((r) => r.id === queueId);
  if (!row) throw new AppError("NOT_FOUND");
  return row;
}

export async function approveAttendance(eventId: string, queueId: string): Promise<void> {
  const row = await findQueueRow(eventId, queueId);
  const event = (await getTable("events")).find((e) => e.id === eventId);
  if (!event) throw new AppError("NOT_FOUND");

  await mutate("activities", (rows) => {
    const idx = rows.findIndex((a) => a.id === event.activityId);
    if (idx === -1) throw new AppError("NOT_FOUND"); // dangling reference
    if (!rows[idx].attendeeIds.includes(row.memberId)) {
      rows[idx] = { ...rows[idx], attendeeIds: [...rows[idx].attendeeIds, row.memberId] };
    }
    return rows;
  });
  await mutateQueue(eventId, (rows) =>
    rows.map((r) => (r.id === queueId ? { ...r, status: "approved" as const } : r)),
  );
  await invalidateAttendanceCaches([row.memberId]);
}

/** Rejection/deletion of an APPROVED row reverses the activity merge (§7-2). */
async function reverseIfApproved(eventId: string, row: AttendanceRecord): Promise<void> {
  if (row.status !== "approved") return;
  const event = (await getTable("events")).find((e) => e.id === eventId);
  if (!event) return;
  await mutate("activities", (rows) =>
    rows.map((a) =>
      a.id === event.activityId
        ? { ...a, attendeeIds: a.attendeeIds.filter((id) => id !== row.memberId) }
        : a,
    ),
  );
  await invalidateAttendanceCaches([row.memberId]);
}

export async function rejectAttendance(eventId: string, queueId: string): Promise<void> {
  const row = await findQueueRow(eventId, queueId);
  await reverseIfApproved(eventId, row);
  await mutateQueue(eventId, (rows) =>
    rows.map((r) => (r.id === queueId ? { ...r, status: "rejected" as const } : r)),
  );
}

export async function deleteAttendanceRecord(eventId: string, queueId: string): Promise<void> {
  const row = await findQueueRow(eventId, queueId);
  await reverseIfApproved(eventId, row);
  await mutateQueue(eventId, (rows) => rows.filter((r) => r.id !== queueId));
}

export async function updateAttendanceTime(
  eventId: string,
  queueId: string,
  patch: { startTime?: string; endTime?: string },
): Promise<void> {
  await mutateQueue(eventId, (rows) => {
    const idx = rows.findIndex((r) => r.id === queueId);
    if (idx === -1) throw new AppError("NOT_FOUND");
    rows[idx] = { ...rows[idx], ...definedOnly(patch) };
    return rows;
  });
}

/** Admin dashboard: pending rows across all events, member names resolved. */
export async function getPendingAttendance() {
  const [queues, memberById, events] = await Promise.all([
    listPendingQueues(),
    getDirectoryIndex(), // 표시용 이름·학과만 — 큐 행 자체는 운영 데이터
    getTable("events"),
  ]);
  const eventById = new Map(events.map((e) => [e.id, e]));
  return queues.flatMap(({ eventId, rows }) =>
    rows.map((r) => ({
      ...r,
      userName: memberById.get(r.memberId)?.name ?? "Unknown",
      userDept: memberById.get(r.memberId)?.department ?? "",
      eventTitle: eventById.get(eventId)?.title ?? "(삭제된 이벤트)",
    })),
  );
}

// ---- cron (BE-35: skeleton + expire; later tasks register their own steps) --

export type CronStep = {
  name: string;
  run: () => Promise<Record<string, number>>;
};

const cronSteps: CronStep[] = [
  {
    name: "expire",
    run: async () => {
      const now = new Date();
      // Count candidates BEFORE the mutation — counting inside the fn would
      // double on conditional-write retries (review low-11).
      const expired = (await getTable("events")).filter(
        (e) => e.status === "active" && expiryOf(e) < now,
      ).length;
      await mutate("events", (rows) =>
        rows.map((e) =>
          e.status === "active" && expiryOf(e) < now
            ? { ...e, status: "expired" as const }
            : e,
        ),
      );
      return { expired };
    },
  },
];

export function registerCronStep(step: CronStep): void {
  if (!cronSteps.some((s) => s.name === step.name)) cronSteps.push(step);
}

export async function runCron(): Promise<Record<string, number>> {
  const results: Record<string, number> = {};
  for (const step of cronSteps) {
    try {
      Object.assign(results, await step.run());
    } catch (e) {
      console.error(`[Cron] step '${step.name}' failed:`, e);
      results[`${step.name}_failed`] = 1;
    }
  }
  return results;
}
