import { beforeEach, describe, expect, it, vi } from "vitest";

vi.mock(
  "$lib/server/data/store",
  () => import("$lib/server/data/store-memory"),
);
vi.mock("$lib/server/mail/dispatch", () => ({
  emitMailEvent: async () => true,
}));

import { __reset } from "$lib/server/data/store-memory";
import {
  _resetDataLayerForTests,
  getTable,
  mutate,
} from "$lib/server/data/tables";
import { invalidateCache } from "$lib/server/cache";
import { AppError } from "$lib/server/core/errors";
import { newId } from "$lib/server/core/id";
import { toKstIso } from "$lib/server/core/time";
import type { Study } from "$lib/server/data/schemas";
import { approveSeminar, submitSeminarRequest } from "./seminar-requests";
import {
  publishSeminar,
  scheduleSeminar,
  updateSeminarSchedule,
} from "./seminars";
import { createStudySession, updateSession } from "./studies";

/**
 * SQL flows write without the zod gate `mutate` has, so a value the stored
 * schema would refuse was committed first and the parse failed after — and
 * from then on the whole table could not be read (audit LA26-2, LC04-1,
 * LA09-5). The services now check every value a flow will store before the
 * flow runs.
 */

const isValidation = (e: unknown) =>
  e instanceof AppError && e.code === "VALIDATION_FAILED";
const future = (h: number) =>
  toKstIso(new Date(Date.now() + h * 60 * 60 * 1000));

beforeEach(async () => {
  await __reset();
  _resetDataLayerForTests({ backoffBaseMs: 1 });
  for (const t of [
    "seminars",
    "seminar-requests",
    "activities",
    "events",
    "studies",
  ])
    await invalidateCache(`table_${t}`);
});

async function publishedSeminarId() {
  const req = await submitSeminarRequest({
    title: "세미나",
    description: "설명",
    prerequisites: "",
    duration: "60분",
    preferredTiming: "",
    presenterIds: ["m1"],
    attachment: "",
    requesterId: "m1",
  });
  await approveSeminar(req.id);
  const [s] = await getTable("seminars");
  await scheduleSeminar(s.id, {
    startsAt: future(48),
    startTime: null,
    endsAt: null,
    location: "27동",
  });
  await publishSeminar(s.id);
  return s.id;
}

describe("updateSeminarSchedule on a published seminar", () => {
  it.each([
    [
      "a clock time the schedule rule refuses",
      {
        startsAt: future(72),
        startTime: "24:00",
        endsAt: null,
        location: "27동",
      },
    ],
    [
      "an end before the start",
      {
        startsAt: future(72),
        startTime: null,
        endsAt: future(70),
        location: "27동",
      },
    ],
    [
      "a start that is not an ISO instant",
      {
        startsAt: "202-01-01T10:00:00+09:00",
        startTime: null,
        endsAt: null,
        location: "27동",
      },
    ],
  ])("refuses %s and leaves every table readable", async (_label, schedule) => {
    const id = await publishedSeminarId();

    await expect(
      updateSeminarSchedule(id, schedule as never),
    ).rejects.toSatisfy(isValidation);

    await invalidateCache("table_seminars");
    await invalidateCache("table_activities");
    await invalidateCache("table_events");
    expect(await getTable("seminars")).toHaveLength(1);
    await getTable("activities");
    await getTable("events");
  });
});

describe("study sessions", () => {
  async function seedStudy(): Promise<Study> {
    const s: Study = {
      id: newId(),
      title: "해석학",
      semester: "26-2",
      textbook: "",
      description: "",
      note: "",
      organizerIds: ["org"],
      participantIds: ["org"],
      pendingParticipantIds: [],
      pendingTransfer: null,
      schedule: [],
      transferHistory: [],
      photos: [],
      status: "recruiting",
      sourceRequestId: null,
    };
    await mutate("studies", (rows) => [...rows, s]);
    return s;
  }

  it("refuses to create a session at a date that is not an ISO instant", async () => {
    const s = await seedStudy();
    await expect(
      createStudySession(s, "202-10-05T19:00:00+09:00", {
        autoGenerated: false,
      }),
    ).rejects.toSatisfy(isValidation);
    await invalidateCache("table_events");
    expect(await getTable("events")).toEqual([]);
  });

  it("refuses to move a session to such a date", async () => {
    const s = await seedStudy();
    const e = await createStudySession(s, future(5), { autoGenerated: false });
    await expect(
      updateSession(s.id, e.id, { dateIso: "2026-02-30T19:00:00" }),
    ).rejects.toSatisfy(isValidation);
    await invalidateCache("table_events");
    await invalidateCache("table_activities");
    expect((await getTable("events"))[0].date.start).toBe(e.date.start);
    await getTable("activities");
  });
});
