import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

vi.mock(
  "$lib/server/data/store",
  () => import("$lib/server/data/store-memory"),
);
vi.mock(
  "$lib/server/data/storage",
  () => import("$lib/server/data/storage-memory"),
);

import { __reset } from "$lib/server/data/store-memory";
import { __reset as __resetStorage } from "$lib/server/data/storage-memory";
import { expectTablesValid } from "$lib/server/data/expect-tables-valid";
import {
  _resetDataLayerForTests,
  getTable,
  mutate,
} from "$lib/server/data/tables";
import { invalidateCache } from "$lib/server/cache";
import { AppError } from "$lib/server/core/errors";
import { newId } from "$lib/server/core/id";
import { toKstIso } from "$lib/server/core/time";
import type { Study } from "$lib/server/data/schemas";
import { createStudySession } from "./studies";
import { createActivity, deleteActivity, deleteStudy } from "./records-admin";

/**
 * flow_delete_study / flow_delete_activity: the "still referenced?" check
 * and the delete share one lock. Before, the check read cached tables, so a
 * session created meanwhile could be left pointing at a deleted study.
 */

const codeOf = (e: unknown) => (e instanceof AppError ? e.code : String(e));

beforeEach(async () => {
  await __reset();
  __resetStorage();
  _resetDataLayerForTests({ backoffBaseMs: 1 });
  for (const t of [
    "activities",
    "events",
    "studies",
    "gallery-dinner",
    "seminars",
  ])
    await invalidateCache(`table_${t}`);
});
afterEach(expectTablesValid);

async function seedStudy(): Promise<Study> {
  const s: Study = {
    id: newId(),
    title: "해석학",
    semester: "26-2",
    textbook: "",
    description: "",
    note: "",
    organizerIds: ["org"],
    participantIds: ["org"],
    pendingParticipantIds: [],
    pendingTransfer: null,
    schedule: [],
    transferHistory: [],
    photos: [],
    status: "recruiting",
    sourceRequestId: null,
  };
  await mutate("studies", (rows) => [...rows, s]);
  return s;
}

describe("deleteStudy ∥ createStudySession", () => {
  it.each([1, 2, 3, 4, 5])(
    "no session outlives its study (run %i)",
    async () => {
      const s = await seedStudy();
      const date = toKstIso(new Date(Date.now() + 3_600_000));

      const [del, add] = await Promise.allSettled([
        deleteStudy(s.id),
        createStudySession(s, date, { autoGenerated: false }),
      ]);

      const studyGone = (await getTable("studies")).length === 0;
      const sessions = (await getTable("events")).filter(
        (e) => e.studyId === s.id,
      );
      if (studyGone) {
        expect(sessions).toEqual([]);
        expect(add.status === "rejected" && codeOf(add.reason)).toBe(
          "NOT_FOUND",
        );
      } else {
        expect(del.status === "rejected" && codeOf(del.reason)).toBe(
          "CONFLICT",
        );
        expect(sessions).toHaveLength(1);
      }
    },
  );
});

describe("deleteActivity", () => {
  it("refuses while a study session points at it, deletes once free", async () => {
    const s = await seedStudy();
    const e = await createStudySession(
      s,
      toKstIso(new Date(Date.now() + 3_600_000)),
      { autoGenerated: false },
    );
    await expect(deleteActivity(e.activityId)).rejects.toSatisfy(
      (err) => codeOf(err) === "CONFLICT",
    );

    const free = await createActivity({
      title: "모임",
      date: { start: toKstIso(new Date()), end: null },
      type: "세미나",
    });
    await deleteActivity(free.id);
    expect((await getTable("activities")).map((a) => a.id)).not.toContain(
      free.id,
    );
    await expect(deleteActivity(free.id)).rejects.toSatisfy(
      (err) => codeOf(err) === "NOT_FOUND",
    );
  });
});
