import { AppError } from "$lib/server/core/errors";
import { newId, randomToken } from "$lib/server/core/id";
import { nowKstIso } from "$lib/server/core/time";
import { currentTerm } from "$lib/server/core/semester";
import { getTable, mutate } from "$lib/server/data/tables";
import { ensureCreated } from "$lib/server/data/idempotency";
import type { SeminarRequest } from "$lib/server/data/schemas";

/** Seminar proposal lifecycle (API-SPEC §5-1, §5-2, §7-2). */

export async function submitSeminarRequest(input: {
  title: string;
  description: string;
  prerequisites: string;
  duration: string;
  presenterIds: string[];
  attachment: string;
  requesterId: string;
}): Promise<SeminarRequest> {
  const row: SeminarRequest = {
    id: newId(),
    ...input,
    status: "pending",
    createdAt: nowKstIso(),
  };
  await mutate("seminar-requests", (rows) => [...rows, row]);
  return row;
}

export async function updateSeminarRequest(
  id: string,
  actor: { memberId: string; isAdmin: boolean },
  patch: Partial<
    Pick<
      SeminarRequest,
      "title" | "description" | "prerequisites" | "duration" | "presenterIds" | "attachment"
    >
  >,
): Promise<void> {
  await mutate("seminar-requests", (rows) => {
    const idx = rows.findIndex((r) => r.id === id);
    if (idx === -1) throw new AppError("NOT_FOUND");
    const row = rows[idx];
    if (row.requesterId !== actor.memberId && !actor.isAdmin) {
      throw new AppError("FORBIDDEN");
    }
    if (row.status !== "pending") throw new AppError("CONFLICT");
    rows[idx] = { ...row, ...patch };
    return rows;
  });
}

/** §5-2 ?/withdraw — the requester's own retraction. */
export async function withdrawSeminarRequest(id: string, memberId: string): Promise<void> {
  await mutate("seminar-requests", (rows) => {
    const idx = rows.findIndex((r) => r.id === id);
    if (idx === -1) throw new AppError("NOT_FOUND");
    if (rows[idx].requesterId !== memberId) throw new AppError("FORBIDDEN");
    if (rows[idx].status !== "pending") throw new AppError("CONFLICT");
    rows[idx] = { ...rows[idx], status: "withdrawn" };
    return rows;
  });
}

/**
 * §7-2 ?/approveSeminar — the ensureCreated chain (§1-6): activity → event →
 * archive record → request status. Announcement mail is a BE-45 concern; the
 * stub below keeps M3 free of M4 code.
 */
export async function approveSeminar(
  id: string,
): Promise<{ request: SeminarRequest; mailFailed: boolean }> {
  const request = (await getTable("seminar-requests")).find((r) => r.id === id);
  if (!request) throw new AppError("NOT_FOUND");
  if (request.status !== "pending") throw new AppError("CONFLICT");

  // Every step is its own ensureCreated so a re-run after ANY mid-sequence
  // failure fills in exactly the missing records (§1-6).
  const activity = await ensureCreated("activities", id, () => ({
    id: newId(),
    title: request.title,
    date: { start: nowKstIso(), end: null },
    type: "세미나" as const,
    attendeeIds: [...request.presenterIds],
    sourceRequestId: id,
  }));

  await ensureCreated("events", id, () => ({
    id: newId(),
    title: request.title,
    date: activity.date,
    type: "세미나" as const,
    status: "active" as const,
    pathId: randomToken(),
    attendCode: randomToken(),
    activityId: activity.id,
    applicantIds: [],
    presenterIds: [...request.presenterIds],
    studyId: null,
    sessionNo: null,
    autoGenerated: false,
    sourceRequestId: id,
  }));

  await ensureCreated("seminars", id, () => ({
    id: newId(),
    title: request.title,
    semester: currentTerm(),
    note: request.description,
    presenterIds: request.presenterIds,
    externalPresenters: "",
    materials: [],
    photos: [],
    activityId: activity.id,
    sourceRequestId: id,
  }));

  await mutate("seminar-requests", (rows) =>
    rows.map((r) => (r.id === id ? { ...r, status: "approved" as const } : r)),
  );

  // BE-45 stub: the all-member announcement lands with the mail milestone.
  const mailFailed = true;
  return { request, mailFailed };
}

export async function rejectSeminar(id: string): Promise<SeminarRequest> {
  const request = (await getTable("seminar-requests")).find((r) => r.id === id);
  if (!request) throw new AppError("NOT_FOUND");
  if (request.status !== "pending") throw new AppError("CONFLICT");
  await mutate("seminar-requests", (rows) =>
    rows.map((r) => (r.id === id ? { ...r, status: "rejected" as const } : r)),
  );
  return request;
}
