import { AppError } from "$lib/server/core/errors";
import { newId, randomToken } from "$lib/server/core/id";
import { nowKstIso } from "$lib/server/core/time";
import { currentTerm } from "$lib/server/core/semester";
import { getTable, mutate } from "$lib/server/data/tables";
import { ensureCreated } from "$lib/server/data/idempotency";
import { promotePendingUpload } from "$lib/server/services/uploads";
import type { SeminarRequest } from "$lib/server/data/schemas";

/** Seminar proposal lifecycle (API-SPEC §5-1, §5-2, §7-2). */

/**
 * 직접 업로드 포스터: staging의 pending 키를 assets로 승격해 최종 키를 반환.
 * 빈 값이면 자동 생성 포스터를 쓰는 것이므로 그대로 빈 문자열.
 */
async function promotePosterIfAny(pendingKey: string): Promise<string> {
  const key = pendingKey.trim();
  if (!key) return "";
  if (!key.startsWith("pending/seminar-poster/")) {
    throw new AppError("VALIDATION_FAILED", { userMessage: "포스터 업로드 정보가 올바르지 않습니다." });
  }
  return promotePendingUpload(key, "seminar-poster", newId());
}

export async function submitSeminarRequest(input: {
  title: string;
  description: string;
  prerequisites: string;
  duration: string;
  presenterIds: string[];
  attachment: string;
  posterPendingKey?: string;
  requesterId: string;
}): Promise<SeminarRequest> {
  const { posterPendingKey = "", ...rest } = input;
  const row: SeminarRequest = {
    id: newId(),
    ...rest,
    posterKey: await promotePosterIfAny(posterPendingKey),
    status: "pending",
    createdAt: nowKstIso(),
  };
  await mutate("seminar-requests", (rows) => [...rows, row]);
  return row;
}

export async function updateSeminarRequest(
  id: string,
  actor: { memberId: string; isAdmin: boolean },
  patch: Partial<
    Pick<
      SeminarRequest,
      "title" | "description" | "prerequisites" | "duration" | "presenterIds" | "attachment"
    >
  >,
  posterPendingKey = "",
): Promise<void> {
  // 새 포스터를 올렸으면 승격해 교체 — mutate 밖에서(외부 I/O). 없으면 유지.
  const promotedPoster = posterPendingKey ? await promotePosterIfAny(posterPendingKey) : null;
  await mutate("seminar-requests", (rows) => {
    const idx = rows.findIndex((r) => r.id === id);
    if (idx === -1) throw new AppError("NOT_FOUND");
    const row = rows[idx];
    if (row.requesterId !== actor.memberId && !actor.isAdmin) {
      throw new AppError("FORBIDDEN");
    }
    if (row.status !== "pending") throw new AppError("CONFLICT");
    rows[idx] = { ...row, ...patch, ...(promotedPoster !== null ? { posterKey: promotedPoster } : {}) };
    return rows;
  });
}

/** §5-2 ?/withdraw — the requester's own retraction. */
export async function withdrawSeminarRequest(id: string, memberId: string): Promise<void> {
  await mutate("seminar-requests", (rows) => {
    const idx = rows.findIndex((r) => r.id === id);
    if (idx === -1) throw new AppError("NOT_FOUND");
    if (rows[idx].requesterId !== memberId) throw new AppError("FORBIDDEN");
    if (rows[idx].status !== "pending") throw new AppError("CONFLICT");
    rows[idx] = { ...rows[idx], status: "withdrawn" };
    return rows;
  });
}

/**
 * §7-2 ?/approveSeminar — the ensureCreated chain (§1-6): activity → event →
 * archive record → request status. Announcement mail is a BE-45 concern; the
 * stub below keeps M3 free of M4 code.
 */
export async function approveSeminar(
  id: string,
): Promise<{ request: SeminarRequest; mailFailed: boolean }> {
  const request = (await getTable("seminar-requests")).find((r) => r.id === id);
  if (!request) throw new AppError("NOT_FOUND");
  if (request.status !== "pending") throw new AppError("CONFLICT");

  // Every step is its own ensureCreated so a re-run after ANY mid-sequence
  // failure fills in exactly the missing records (§1-6).
  const activity = await ensureCreated("activities", id, () => ({
    id: newId(),
    title: request.title,
    date: { start: nowKstIso(), end: null },
    type: "세미나" as const,
    attendeeIds: [...request.presenterIds],
    sourceRequestId: id,
  }));

  await ensureCreated("events", id, () => ({
    id: newId(),
    title: request.title,
    date: activity.date,
    type: "세미나" as const,
    status: "active" as const,
    pathId: randomToken(),
    attendCode: randomToken(),
    activityId: activity.id,
    applicantIds: [],
    presenterIds: [...request.presenterIds],
    studyId: null,
    sessionNo: null,
    autoGenerated: false,
    sourceRequestId: id,
  }));

  await ensureCreated("seminars", id, () => ({
    id: newId(),
    title: request.title,
    semester: currentTerm(),
    note: request.description,
    presenterIds: request.presenterIds,
    externalPresenters: "",
    materials: [],
    photos: [],
    activityId: activity.id,
    sourceRequestId: id,
  }));

  // The pending→approved flip is a compare-and-set INSIDE the mutate: the
  // entry check above reads a cache that can be 15s stale, so two concurrent
  // approvals could both pass it — but only one wins this CAS, and only the
  // winner sends the all-member announcement (review M3).
  await mutate("seminar-requests", (rows) =>
    rows.map((r) => {
      if (r.id !== id) return r;
      if (r.status !== "pending") throw new AppError("CONFLICT");
      return { ...r, status: "approved" as const };
    }),
  );

  // BE-45: all-member announcement (Bcc, opted-in only). Failure never
  // propagates — the CAS above guarantees exactly one sender.
  const { sendSeminarAnnouncement } = await import("$lib/server/mail/announcements");
  const mailFailed = !(await sendSeminarAnnouncement({
    title: request.title,
    description: request.description,
  }));
  return { request, mailFailed };
}

export async function rejectSeminar(id: string): Promise<SeminarRequest> {
  const request = (await getTable("seminar-requests")).find((r) => r.id === id);
  if (!request) throw new AppError("NOT_FOUND");
  await mutate("seminar-requests", (rows) =>
    rows.map((r) => {
      if (r.id !== id) return r;
      if (r.status !== "pending") throw new AppError("CONFLICT"); // CAS
      return { ...r, status: "rejected" as const };
    }),
  );
  return request;
}
