import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

vi.mock(
  "$lib/server/data/store",
  () => import("$lib/server/data/store-memory"),
);

import { __reset } from "$lib/server/data/store-memory";
import { expectTablesValid } from "$lib/server/data/expect-tables-valid";
import {
  _resetDataLayerForTests,
  getTable,
  mutate,
} from "$lib/server/data/tables";
import { invalidateCache } from "$lib/server/cache";
import { AppError } from "$lib/server/core/errors";
import { newId } from "$lib/server/core/id";
import { toKstIso } from "$lib/server/core/time";
import type { Study } from "$lib/server/data/schemas";
import {
  cancelSession,
  createStudySession,
  setStudyStatus,
  updateSession,
} from "./studies";

/**
 * flow_create_study_session / flow_update_study_session. Session numbers
 * were computed from a cached read, so two sessions created at once could
 * both become "3회차"; a correction moved the event and its activity in two
 * writes.
 */

const at = (h: number) => toKstIso(new Date(Date.now() + h * 60 * 60 * 1000));

beforeEach(async () => {
  await __reset();
  _resetDataLayerForTests({ backoffBaseMs: 1 });
  for (const t of ["activities", "events", "studies"])
    await invalidateCache(`table_${t}`);
});
afterEach(expectTablesValid);

async function seedStudy(): Promise<Study> {
  const s: Study = {
    id: newId(),
    title: "해석학",
    semester: "26-2",
    textbook: "",
    description: "",
    note: "",
    organizerIds: ["org"],
    participantIds: ["org"],
    pendingParticipantIds: [],
    pendingTransfer: null,
    schedule: [],
    transferHistory: [],
    photos: [],
    status: "recruiting",
    sourceRequestId: null,
  };
  await mutate("studies", (rows) => [...rows, s]);
  return s;
}

describe("createStudySession", () => {
  it("numbers sessions created at once without a duplicate", async () => {
    const s = await seedStudy();

    await Promise.all(
      [1, 2, 3, 4].map((h) =>
        createStudySession(s, at(h), { autoGenerated: false }),
      ),
    );

    const numbers = (await getTable("events")).map((e) => e.sessionNo).sort();
    expect(numbers).toEqual([1, 2, 3, 4]);
    expect(await getTable("activities")).toHaveLength(4);
  });

  it("names a session by its number when no title is given", async () => {
    const s = await seedStudy();
    await createStudySession(s, at(1), { autoGenerated: false });
    const second = await createStudySession(s, at(2), {
      autoGenerated: false,
    });
    expect(second.title).toBe("해석학 2회차");
    const own = await createStudySession(s, at(3), {
      title: "특강",
      autoGenerated: false,
    });
    expect(own.title).toBe("특강");
  });

  it("returns the same session for the same slot", async () => {
    const s = await seedStudy();
    const slot = at(1); // one instant: at() reads the clock each call
    const a = await createStudySession(s, slot, { autoGenerated: false });
    const b = await createStudySession(s, slot, { autoGenerated: false });
    expect(b.id).toBe(a.id);
    expect(await getTable("events")).toHaveLength(1);
  });

  it("refuses a cancelled slot with the organizer-facing message", async () => {
    const s = await seedStudy();
    const date = at(1);
    const e = await createStudySession(s, date, { autoGenerated: false });
    await cancelSession(s.id, e.id);

    await expect(
      createStudySession(s, date, { autoGenerated: false }),
    ).rejects.toSatisfy(
      (err) =>
        err instanceof AppError &&
        err.code === "CONFLICT" &&
        err.userMessage ===
          "취소된 회차와 같은 일시입니다. 다른 일시를 선택해 주세요.",
    );
  });

  it("refuses a study finished after the page read it", async () => {
    const s = await seedStudy(); // the organizer's copy says "recruiting"
    await setStudyStatus(s.id, "ongoing");
    await setStudyStatus(s.id, "finished");

    await expect(
      createStudySession(s, at(1), { autoGenerated: false }),
    ).rejects.toSatisfy((e) => e instanceof AppError && e.code === "CONFLICT");
    expect(await getTable("events")).toEqual([]);
  });
});

describe("updateSession", () => {
  it("moves the event and its activity together", async () => {
    const s = await seedStudy();
    const e = await createStudySession(s, at(1), { autoGenerated: false });
    const moved = at(5);

    await updateSession(s.id, e.id, { title: "보강", dateIso: moved });

    const [event] = await getTable("events");
    const [activity] = await getTable("activities");
    for (const row of [event, activity]) {
      expect(row.title).toBe("보강");
      expect(row.date).toEqual({ start: moved, end: null });
    }
    // the slot keeps its original key
    expect(event.sourceRequestId).toBe(`${s.id}:${e.date.start}`);
  });

  it("keeps what the patch leaves out", async () => {
    const s = await seedStudy();
    const e = await createStudySession(s, at(1), { autoGenerated: false });

    await updateSession(s.id, e.id, { title: "제목만" });

    const [event] = await getTable("events");
    expect(event.title).toBe("제목만");
    expect(event.date).toEqual(e.date);
  });

  it("refuses an event of another study", async () => {
    const s = await seedStudy();
    const other = await seedStudy();
    const e = await createStudySession(s, at(1), { autoGenerated: false });

    await expect(
      updateSession(other.id, e.id, { title: "x" }),
    ).rejects.toSatisfy(
      (err) => err instanceof AppError && err.code === "NOT_FOUND",
    );
  });
});
