import { beforeEach, describe, expect, it, vi } from "vitest";

vi.mock("$lib/server/data/s3", () => import("$lib/server/data/s3-memory"));

import { __reset } from "$lib/server/data/s3-memory";
import { _resetDataLayerForTests, getTable, mutate } from "$lib/server/data/tables";
import { invalidateCache } from "$lib/server/cache";
import { newId } from "$lib/server/core/id";
import { nowKstIso, toKstIso } from "$lib/server/core/time";
import { AppError } from "$lib/server/core/errors";
import type { Member, Study } from "$lib/server/data/schemas";
import {
  acceptParticipant,
  acceptTransfer,
  approveStudy,
  cancelSession,
  createStudySession,
  declineTransfer,
  joinStudy,
  leaveStudy,
  proposeTransfer,
  registerSchedule,
  saveStudyAttendance,
  setStudyStatus,
  studySessionCronStep,
  submitStudyRequest,
} from "./studies";

const future = () => toKstIso(new Date(Date.now() + 60 * 60 * 1000));
const past = () => toKstIso(new Date(Date.now() - 60 * 60 * 1000));

async function seedMember(id: string, name = "회원"): Promise<void> {
  const m: Member = {
    id, name, department: "수리과학부", joinedAt: "2024-03-01",
    status: "regular", statusChangedAt: nowKstIso(), withdrawal: null,
    isAlumni: true, alumniRevoked: false, roles: [], isAdmin: false,
    publicContact: null, project: null, sourceRequestId: null,
  };
  await mutate("members", (rows) => [...rows, m]);
}

async function seedStudy(over: Partial<Study> = {}): Promise<Study> {
  const s: Study = {
    id: newId(), title: "해석학", semester: "26-2", textbook: "", description: "",
    note: "", organizerIds: ["org"], participantIds: ["org"],
    pendingParticipantIds: [], pendingTransfer: null, schedule: [],
    transferHistory: [], photos: [], status: "recruiting", sourceRequestId: null,
    ...over,
  };
  await mutate("studies", (rows) => [...rows, s]);
  return s;
}

beforeEach(async () => {
  __reset();
  _resetDataLayerForTests({ backoffBaseMs: 1 });
  for (const t of ["studies", "study-requests", "events", "activities", "members"]) {
    await invalidateCache(`table_${t}`);
  }
});

describe("proposal → approval (STU-01 / ADM-16)", () => {
  it("approval creates the study with the requester as organizer AND participant", async () => {
    const req = await submitStudyRequest({
      title: "위상수학", textbook: "Munkres", description: "", semester: "26-2",
      requesterId: "m-req",
    });
    await approveStudy(req.id);

    const study = (await getTable("studies"))[0];
    expect(study.organizerIds).toEqual(["m-req"]);
    expect(study.participantIds).toContain("m-req");
    expect(study.status).toBe("recruiting");
    expect((await getTable("study-requests"))[0].status).toBe("approved");

    // idempotent re-run
    await expect(approveStudy(req.id)).rejects.toSatisfy(
      (e) => e instanceof AppError && e.code === "CONFLICT",
    );
    expect(await getTable("studies")).toHaveLength(1);
  });
});

describe("participation (STU-02/04)", () => {
  it("join gates on recruiting; accept moves pending → participant", async () => {
    const s = await seedStudy();
    await joinStudy(s.id, "m1");
    await joinStudy(s.id, "m1"); // idempotent
    expect((await getTable("studies"))[0].pendingParticipantIds).toEqual(["m1"]);

    await acceptParticipant(s.id, "m1");
    const updated = (await getTable("studies"))[0];
    expect(updated.participantIds).toContain("m1");
    expect(updated.pendingParticipantIds).toEqual([]);

    await setStudyStatus(s.id, "ongoing");
    await expect(joinStudy(s.id, "m2")).rejects.toSatisfy(
      (e) => e instanceof AppError && e.code === "STUDY_NOT_RECRUITING",
    );
  });

  it("the organizer cannot leave — hand over first", async () => {
    const s = await seedStudy();
    await expect(leaveStudy(s.id, "org")).rejects.toSatisfy(
      (e) => e instanceof AppError && e.code === "CONFLICT",
    );
  });
});

describe("sessions (STU-06 / BE-49)", () => {
  it("manual + cron creation share the composite key — never double-creates", async () => {
    const s = await seedStudy();
    const date = past();
    await registerSchedule(s.id, [date]);

    // Organizer clicks manually before the cron fires:
    await createStudySession(s, date, { autoGenerated: false });
    // Then the cron runs over the same schedule entry:
    const result = await studySessionCronStep.run();

    const events = (await getTable("events")).filter((e) => e.studyId === s.id);
    expect(events).toHaveLength(1); // composite key dedupe
    expect(result.generated).toBe(1); // cron linked the entry to the existing event
    const study = (await getTable("studies"))[0];
    expect(study.schedule[0].generatedEventId).toBe(events[0].id);
  });

  it("cron generates due entries only, numbers sessions sequentially", async () => {
    const s = await seedStudy();
    await registerSchedule(s.id, [past(), future()]);
    await studySessionCronStep.run();

    const events = (await getTable("events")).filter((e) => e.studyId === s.id);
    expect(events).toHaveLength(1); // future entry untouched
    expect(events[0].sessionNo).toBe(1);
    expect(events[0].autoGenerated).toBe(true);

    const again = await studySessionCronStep.run();
    expect(again.generated).toBe(0); // idempotent
  });

  it("cancelled sessions are terminal and unhooked from regeneration", async () => {
    const s = await seedStudy();
    const date = past();
    await registerSchedule(s.id, [date]);
    const event = await createStudySession(s, date, { autoGenerated: false });
    await cancelSession(s.id, event.id);

    expect((await getTable("events"))[0].status).toBe("cancelled");
    const result = await studySessionCronStep.run();
    expect(result.generated).toBe(0); // schedule entry consumed
  });
});

describe("organizer handover (STU-07 / BE-50)", () => {
  it("two-phase: propose → accept replaces organizer and records history", async () => {
    await seedMember("m-new", "김수학");
    const s = await seedStudy();
    await proposeTransfer(s.id, "org", "m-new");

    // duplicate proposal blocked
    await expect(proposeTransfer(s.id, "org", "m-new")).rejects.toSatisfy(
      (e) => e instanceof AppError && e.code === "CONFLICT",
    );

    await acceptTransfer(s.id, "m-new");
    const updated = (await getTable("studies"))[0];
    expect(updated.organizerIds).toEqual(["m-new"]);
    expect(updated.participantIds).toContain("m-new");
    expect(updated.pendingTransfer).toBeNull();
    expect(updated.transferHistory.at(-1)).toMatchObject({
      from: "org", to: "m-new", byAdmin: false,
    });
  });

  it("blocks self-transfer and unknown/withdrawn targets", async () => {
    const s = await seedStudy();
    await expect(proposeTransfer(s.id, "org", "org")).rejects.toSatisfy(
      (e) => e instanceof AppError && e.code === "VALIDATION_FAILED",
    );
    await expect(proposeTransfer(s.id, "org", "ghost")).rejects.toSatisfy(
      (e) => e instanceof AppError && e.code === "VALIDATION_FAILED",
    );
  });

  it("decline clears the proposal; a stranger cannot accept", async () => {
    await seedMember("m-new");
    const s = await seedStudy();
    await proposeTransfer(s.id, "org", "m-new");

    await expect(acceptTransfer(s.id, "someone-else")).rejects.toSatisfy(
      (e) => e instanceof AppError && e.code === "NOT_FOUND",
    );
    await declineTransfer(s.id, "m-new");
    expect((await getTable("studies"))[0].pendingTransfer).toBeNull();
    expect((await getTable("studies"))[0].organizerIds).toEqual(["org"]);
  });
});

describe("attendance (STU-05 / BE-51)", () => {
  it("merge rule: walk-in check-ins survive the organizer's save", async () => {
    const s = await seedStudy({ participantIds: ["org", "p1", "p2"] });
    const event = await createStudySession(s, future(), { autoGenerated: false });
    await mutate("activities", (rows) =>
      rows.map((a) => (a.id === event.activityId ? { ...a, attendeeIds: ["walkin"] } : a)),
    );

    await saveStudyAttendance(s, event.id, ["p1"]);
    expect((await getTable("activities"))[0].attendeeIds.sort()).toEqual(
      ["p1", "walkin"].sort(),
    );

    await expect(saveStudyAttendance(s, event.id, ["outsider"])).rejects.toSatisfy(
      (e) => e instanceof AppError && e.code === "VALIDATION_FAILED",
    );
  });

  it("rejects a session belonging to another study", async () => {
    const s1 = await seedStudy();
    const s2 = await seedStudy({ title: "대수학" });
    const event = await createStudySession(s1, future(), { autoGenerated: false });
    await expect(saveStudyAttendance(s2, event.id, [])).rejects.toSatisfy(
      (e) => e instanceof AppError && e.code === "NOT_FOUND",
    );
  });
});
