import { beforeEach, describe, expect, it, vi } from "vitest";

vi.mock(
  "$lib/server/data/store",
  () => import("$lib/server/data/store-memory"),
);
vi.mock("$lib/server/mail/dispatch", () => ({
  emitMailEvent: async () => true,
}));

import { __putRawDoc, __reset, __sql } from "./store-memory";
import { expectTablesValid } from "./expect-tables-valid";
import { _resetDataLayerForTests, getQueue, getTable } from "./tables";
import { invalidateCache } from "$lib/server/cache";
import { AppError } from "$lib/server/core/errors";
import { callFlow, type FlowResult } from "./flows";
import type { Seminar } from "./schemas";
import {
  cancelSeminar,
  publishSeminar,
  seminarHasStarted,
} from "$lib/server/services/seminars";
import {
  approveAttendance,
  checkIn,
  createEventWithActivity,
  rejectAttendance,
} from "$lib/server/services/events";

/**
 * Contracts of the SQL flows the layer audit found broken
 * (docs/code-audit/files/supabase/migrations/20260928000000_atomic_flows.md).
 */

const codeOf = (e: unknown) => (e instanceof AppError ? e.code : String(e));
const FUTURE = "2031-10-15T19:00:00+09:00";

beforeEach(async () => {
  await __reset();
  _resetDataLayerForTests({ backoffBaseMs: 1 });
  for (const t of ["seminars", "activities", "events", "members"])
    await invalidateCache(`table_${t}`);
});

const put = (name: string, rows: unknown[]) =>
  __putRawDoc("table", name, { schemaVersion: 1, rows });

const legacySeminar = (over: Partial<Seminar> = {}): Seminar => ({
  id: "s1",
  title: "이주 세미나",
  semester: "31-2",
  note: "",
  description: "",
  presenterIds: ["p1"],
  externalPresenters: "",
  materials: [],
  photos: [],
  posterKey: "",
  preferredTiming: "",
  publicationStatus: "published",
  kind: null,
  durationMinutes: null,
  prerequisites: "",
  announce: true,
  schedule: {
    startsAt: FUTURE,
    startTime: "19:00",
    endsAt: null,
    location: "27동",
  },
  announcedAt: null,
  semesterPinned: false,
  activityId: "a1",
  sourceRequestId: null,
  ...over,
});
const legacyActivity = {
  id: "a1",
  title: "이주 세미나",
  date: { start: FUTURE, end: null },
  type: "세미나",
  attendeeIds: ["p1"],
  sourceRequestId: null,
};
const legacyEvent = {
  id: "e1",
  title: "이주 세미나",
  date: { start: FUTURE, end: null },
  type: "세미나",
  status: "active",
  pathId: "p",
  attendCode: "c",
  activityId: "a1",
  applicantIds: [],
  presenterIds: ["p1"],
  studyId: null,
  sessionNo: null,
  autoGenerated: false,
  sourceRequestId: null,
};

// LA43-1 🔴 — every migrated seminar is published with no anchor and
// announcedAt null, so the board offers "공지 재발송" on all of them.
describe("publishing a seminar linked by activityId (no anchor)", () => {
  it("reuses its activity and event instead of creating a second pair", async () => {
    await put("seminars", [legacySeminar()]);
    await put("activities", [legacyActivity]);
    await put("events", [legacyEvent]);

    await publishSeminar("s1");

    expect((await getTable("activities")).map((a) => a.id)).toEqual(["a1"]);
    expect((await getTable("events")).map((e) => e.id)).toEqual(["e1"]);
    expect((await getTable("seminars"))[0].activityId).toBe("a1");

    await cancelSeminar("s1", { memberId: "admin", isAdmin: true });
    expect((await getTable("events"))[0].status).toBe("cancelled");
    await expectTablesValid();
  });

  it("keeps the seminar and an anchored event on the same activity", async () => {
    await put("seminars", [legacySeminar()]);
    await put("activities", [legacyActivity]);
    await put("events", [{ ...legacyEvent, sourceRequestId: "seminar:s1" }]);

    await publishSeminar("s1");

    const [event] = await getTable("events");
    expect((await getTable("activities")).map((a) => a.id)).toEqual(["a1"]);
    expect((await getTable("seminars"))[0].activityId).toBe(event.activityId);
  });
});

// LA43-2 — a guard that compares a missing argument lets NULL through to the
// most destructive branch. Each flow now refuses missing arguments.
describe("flows refuse missing arguments", () => {
  it.each([
    ["flow_decide_attendance", { eventId: "e1", queueId: "q1" }],
    ["flow_member_withdrawal", { memberId: "m1", actorId: "a", now: FUTURE }],
    ["flow_cancel_seminar", { id: "s1", isAdmin: false, now: FUTURE }],
    ["flow_update_seminar_schedule", { id: "s1" }],
    [
      "flow_update_seminar_schedule",
      {
        id: "s1",
        schedule: { startsAt: FUTURE, location: "27동" },
      },
    ],
    ["flow_update_seminar_record", { patch: { title: "x" } }],
    ["flow_update_seminar_record", { id: "s1", patch: [] }],
    [
      "flow_create_study_session",
      {
        studyId: "st1",
        activityId: "a",
        eventId: "e",
        pathId: "p",
        attendCode: "c",
      },
    ],
    ["flow_check_in", { eventId: "e1", memberId: "m1", id: "r1" }],
    [
      "flow_save_presenter_attendance",
      { eventId: "e1", presenterId: "p1", seminarTypes: ["세미나"] },
    ],
    [
      "flow_save_presenter_attendance",
      { eventId: "e1", presenterId: "p1", attendeeIds: [] },
    ],
  ] as [`flow_${string}`, Record<string, unknown>][])(
    "%s",
    async (fn, args) => {
      await expect(callFlow(fn, args)).rejects.toSatisfy(
        (e) => codeOf(e) === "VALIDATION_FAILED",
      );
    },
  );

  it("an empty string counts as missing", async () => {
    await expect(
      callFlow("flow_decide_attendance", {
        eventId: "e1",
        queueId: "q1",
        decision: "",
      }),
    ).rejects.toSatisfy((e) => codeOf(e) === "VALIDATION_FAILED");
  });
});

// LA43-3 — rejecting one approved check-in removed the member's credit even
// when another approved check-in on the same activity still justified it.
describe("rejecting an approved check-in", () => {
  it("keeps the credit another approved check-in on the activity justifies", async () => {
    const e1 = await createEventWithActivity({
      title: "세미나",
      startIso: FUTURE,
      type: "세미나",
      status: "active",
    });
    // a second session of the same activity
    const events = await getTable("events");
    const e2 = { ...events[0], id: "e2", pathId: "p2", attendCode: "c2" };
    await put("events", [...events, e2]);
    await invalidateCache("table_events");

    const r1 = await checkIn(e1, "m1");
    const r2 = await checkIn(e2 as never, "m1");
    await approveAttendance(e1.id, r1.id);
    await approveAttendance("e2", r2.id);

    await rejectAttendance(e1.id, r1.id);

    const activity = (await getTable("activities"))[0];
    expect(activity.attendeeIds).toContain("m1");
    expect((await getQueue("e2"))[0].status).toBe("approved");
  });

  it("keeps a presenter's credit", async () => {
    const e = await createEventWithActivity({
      title: "세미나",
      startIso: FUTURE,
      type: "세미나",
      status: "active",
      presenterIds: ["p1"],
    } as never);
    const r = await checkIn(e, "p1");
    await approveAttendance(e.id, r.id);
    await rejectAttendance(e.id, r.id);
    expect((await getTable("activities"))[0].attendeeIds).toContain("p1");
  });
});

// LA43-4 — the cancel flow's "has it started" rule mirrors seminarHasStarted.
describe("app_seminar_started mirrors seminarHasStarted", () => {
  it.each([
    [
      { publicationStatus: "published", schedule: null },
      "2031-01-01T00:00:00+09:00",
    ],
    [
      { publicationStatus: "unscheduled", schedule: null },
      "2031-01-01T00:00:00+09:00",
    ],
    [
      {
        publicationStatus: "scheduled",
        schedule: {
          startsAt: FUTURE,
          startTime: null,
          endsAt: null,
          location: "x",
        },
      },
      "2031-10-15T18:59:59+09:00",
    ],
    [
      {
        publicationStatus: "scheduled",
        schedule: {
          startsAt: FUTURE,
          startTime: null,
          endsAt: null,
          location: "x",
        },
      },
      "2031-10-15T19:00:00+09:00",
    ],
    [
      { publicationStatus: "cancelled", schedule: null },
      "2031-01-01T00:00:00+09:00",
    ],
  ] as [Partial<Seminar>, string][])("%o at %s", async (over, now) => {
    const s = legacySeminar(over);
    const [row] = await __sql<{ started: boolean }>(
      "select app_seminar_started($1::jsonb, $2::timestamptz) as started",
      [JSON.stringify(s), now],
    );
    vi.useFakeTimers({ toFake: ["Date"] });
    vi.setSystemTime(new Date(now));
    try {
      expect(row.started).toBe(seminarHasStarted(s));
    } finally {
      vi.useRealTimers();
    }
  });
});

// LC04-2 — "changed" (which decides the change notice) compared startsAt,
// endsAt and location only. A time that became known, or went back to 미정,
// changes what the notice and the member pages say, yet counted as no change.
describe("flow_update_seminar_schedule: changed", () => {
  const schedule = legacySeminar().schedule!;
  const changed = async (next: object) =>
    (
      await callFlow<FlowResult & { changed: boolean }>(
        "flow_update_seminar_schedule",
        { id: "s1", schedule: { ...schedule, ...next }, now: FUTURE },
      )
    ).changed;

  it("is false for the same schedule saved again", async () => {
    await put("seminars", [legacySeminar()]);
    expect(await changed({})).toBe(false);
  });

  it("is true when only the start time became known or unknown", async () => {
    await put("seminars", [
      legacySeminar({ schedule: { ...schedule, startTime: null } }),
    ]);
    expect(await changed({ startTime: "19:00" })).toBe(true);
    expect(await changed({ startTime: null })).toBe(true);
  });
});

// LA44-1 — a null publicationStatus was treated as present by the backfill.
describe("publicationStatus backfill", () => {
  it("also fills a key that is present but null", async () => {
    await put("seminars", [{ ...legacySeminar(), publicationStatus: null }]);
    const { default: sql } =
      await import("/supabase/migrations/20260928000100_seminar_publication_status.sql?raw");
    await __sql(sql);
    await invalidateCache("table_seminars");
    expect((await getTable("seminars"))[0].publicationStatus).toBe("published");
  });
});

// LA43-4 — the other two helpers have no single TS twin; their rules are
// pinned here by truth table instead.
describe("app_seminar_status / app_is_seminar_event", () => {
  const status = async (row: object) =>
    (
      await __sql<{ s: string }>("select app_seminar_status($1::jsonb) as s", [
        JSON.stringify(row),
      ])
    )[0].s;

  it("reads a missing or null status as published, anything else as written", async () => {
    expect(await status({})).toBe("published");
    expect(await status({ publicationStatus: null })).toBe("published");
    expect(await status({ publicationStatus: "cancelled" })).toBe("cancelled");
  });

  const belongs = async (event: object, seminar: object) =>
    (
      await __sql<{ b: boolean }>(
        "select app_is_seminar_event($1::jsonb, $2::jsonb) as b",
        [JSON.stringify(event), JSON.stringify(seminar)],
      )
    )[0].b;

  it("counts an event anchored to the seminar, or on its activity", async () => {
    const s = { id: "s1", activityId: "a1" };
    expect(
      await belongs({ sourceRequestId: "seminar:s1", activityId: "x" }, s),
    ).toBe(true);
    expect(await belongs({ sourceRequestId: null, activityId: "a1" }, s)).toBe(
      true,
    );
    expect(
      await belongs({ sourceRequestId: "seminar:s2", activityId: "x" }, s),
    ).toBe(false);
    expect(
      await belongs(
        { sourceRequestId: null, activityId: "a1" },
        { id: "s1", activityId: null },
      ),
    ).toBe(false);
  });
});
