-- ============================================================================
-- 20260928000000_atomic_flows.sql — multi-document flows as plpgsql functions
--
-- Design : docs/spec/ATOMIC-FLOWS.md (decision 2026-09-27, option B)
-- Run on : BOTH prod and dev, BEFORE deploying code that calls these
--          functions. Expand-only: the currently deployed code ignores them.
--          Idempotent — safe to re-run.
-- Also   : applied in-process by PGlite for tests and DATA_BACKEND=memory
--          (src/lib/server/data/store-memory.ts), so every statement must run
--          on plain Postgres without Supabase roles.
--
-- Conventions
--   * Every flow is `flow_<name>(p jsonb) returns jsonb`; PostgREST calls it as
--     rpc('flow_<name>', { p: {...} }).
--   * Failures RAISE a bare app error code as the message (NOT_FOUND, CONFLICT,
--     VALIDATION_FAILED, EVENT_NOT_OPEN, FORBIDDEN); the whole transaction
--     rolls back. The TS side maps the message to AppError.
--   * ids and timestamps come IN as arguments (generated by TS: ULID, KST ISO)
--     so SQL-written rows have exactly the shapes TS writes.
--   * Returns { "touched": [table names...], ... } — TS invalidates caches of
--     the touched tables.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1. Document helpers
-- ---------------------------------------------------------------------------

-- rows[] of a table document ('[]' when the document does not exist yet)
create or replace function app_rows(p_name text) returns jsonb
language sql stable set search_path = public as $$
  select coalesce(
    (select doc -> 'rows' from app_tables where name = p_name),
    '[]'::jsonb)
$$;

-- Lock table documents for the rest of the transaction, in name order (no
-- deadlocks between flows). Missing documents are created empty first so
-- they can be locked too — readers treat "missing" and "empty" alike.
create or replace function app_lock(p_names text[]) returns void
language plpgsql set search_path = public as $$
begin
  insert into app_tables (name, version, doc)
    select n, 1, jsonb_build_object('schemaVersion', 1, 'rows', '[]'::jsonb)
    from unnest(p_names) as n
    on conflict (name) do nothing;
  perform 1 from app_tables where name = any (p_names) order by name for update;
end $$;

-- Replace a (locked) table document's rows and bump its version — the same
-- version CAS the TS writers use, so a concurrent TS mutate retries.
create or replace function app_put(p_name text, p_rows jsonb) returns void
language plpgsql set search_path = public as $$
begin
  update app_tables
     set doc = jsonb_set(doc, '{rows}', coalesce(p_rows, '[]'::jsonb)),
         version = version + 1
   where name = p_name;
  if not found then
    raise exception 'app_put: % is not locked/created', p_name;
  end if;
end $$;

-- The row with this id, or NULL.
create or replace function app_find(p_rows jsonb, p_id text) returns jsonb
language sql immutable as $$
  select r from jsonb_array_elements(p_rows) as r where r ->> 'id' = p_id limit 1
$$;

-- rows[] without the row(s) matching a predicate key/value.
create or replace function app_without(p_rows jsonb, p_key text, p_value text)
returns jsonb language sql immutable as $$
  select coalesce(jsonb_agg(r), '[]'::jsonb)
    from jsonb_array_elements(p_rows) as r
   where r ->> p_key is distinct from p_value
$$;

-- rows[] with the row of this id replaced by p_row.
create or replace function app_replace(p_rows jsonb, p_id text, p_row jsonb)
returns jsonb language sql immutable as $$
  select coalesce(jsonb_agg(case when r ->> 'id' = p_id then p_row else r end), '[]'::jsonb)
    from jsonb_array_elements(p_rows) as r
$$;

-- Attendance queues live one document per event in app_queues.
create or replace function app_queue_lock(p_event_ids text[]) returns void
language plpgsql set search_path = public as $$
begin
  perform 1 from app_queues where event_id = any (p_event_ids) order by event_id for update;
end $$;

create or replace function app_queue_rows(p_event_id text) returns jsonb
language sql stable set search_path = public as $$
  select coalesce(
    (select doc -> 'rows' from app_queues where event_id = p_event_id),
    '[]'::jsonb)
$$;

create or replace function app_queue_delete(p_event_id text) returns void
language sql set search_path = public as $$
  delete from app_queues where event_id = p_event_id
$$;

-- Replace a (locked) queue document's rows and bump its version.
create or replace function app_queue_put(p_event_id text, p_rows jsonb) returns void
language plpgsql set search_path = public as $$
begin
  update app_queues
     set doc = jsonb_set(doc, '{rows}', coalesce(p_rows, '[]'::jsonb)),
         version = version + 1
   where event_id = p_event_id;
  if not found then
    raise exception 'app_queue_put: queue % is not locked/created', p_event_id;
  end if;
end $$;

-- JSON null and a missing key alike → SQL NULL.
create or replace function app_nullable(p_value jsonb) returns jsonb
language sql immutable as $$
  select case when p_value is null or jsonb_typeof(p_value) = 'null' then null else p_value end
$$;

-- Is the event open for check-in at p_now? Mirror of services/events.ts
-- effectiveStatus: an active event closes at date.end, or without one at the
-- end of its start's KST day.
create or replace function app_event_open(p_event jsonb, p_now timestamptz)
returns boolean language sql stable as $$
  select p_event ->> 'status' = 'active'
     and coalesce(
           (app_nullable(p_event -> 'date' -> 'end') #>> '{}')::timestamptz,
           (date_trunc('day', ((p_event -> 'date' ->> 'start')::timestamptz at time zone 'UTC')
                              + interval '9 hours')
            + interval '1 day' - interval '9 hours') at time zone 'UTC'
         ) >= p_now
$$;

-- ---------------------------------------------------------------------------
-- 1b. Seminar rules (mirrors of services/seminars.ts and core/semester.ts —
--     keep them in step)
-- ---------------------------------------------------------------------------

-- The regular term an instant falls in, by the KST calendar: Mar–Aug → YY-1,
-- Sep–Feb → YY-2 (Jan/Feb belong to the previous year's second term).
create or replace function app_term_of(p_at text) returns text
language sql stable as $$
  select case
    when extract(month from k) between 3 and 8
      then lpad((extract(year from k)::int % 100)::text, 2, '0') || '-1'
    else lpad(((extract(year from k)::int
                - case when extract(month from k) >= 9 then 0 else 1 end) % 100)::text,
              2, '0') || '-2'
  end
  from (select (p_at::timestamptz at time zone 'UTC') + interval '9 hours' as k) as t
$$;

-- May the term be re-derived from the schedule? Not when an admin pinned it,
-- nor for a vacation term (YY-S / YY-W), which derivation cannot express.
create or replace function app_may_derive_semester(p_sem jsonb) returns boolean
language sql immutable as $$
  select not coalesce((p_sem ->> 'semesterPinned')::boolean, false)
     and coalesce(p_sem ->> 'semester', '') !~ '^\d{2}-[SW]$'
$$;

-- Rows written before publicationStatus existed are published.
create or replace function app_seminar_status(p_sem jsonb) returns text
language sql immutable as $$
  select coalesce(p_sem ->> 'publicationStatus', 'published')
$$;

-- Events that belong to a seminar: anchored to it ('seminar:<id>'), or —
-- for migrated rows without an anchor — hanging off its activity.
create or replace function app_is_seminar_event(p_event jsonb, p_sem jsonb)
returns boolean language sql immutable as $$
  select p_event ->> 'sourceRequestId' = 'seminar:' || (p_sem ->> 'id')
      or (p_sem ->> 'activityId' is not null
          and p_event ->> 'activityId' = p_sem ->> 'activityId')
$$;

-- ---------------------------------------------------------------------------
-- 2. Flows
-- ---------------------------------------------------------------------------

-- Delete a seminar record (admin). A non-published (cancelled/unpublished)
-- seminar is what hides its activity (services/visibility.ts), so deleting it
-- also retires that activity with its sessions and queues — refused while
-- attendance evidence remains (credit beyond the presenters' automatic one,
-- or a pending/approved check-in) or while anything else hangs off the
-- activity (another seminar, a gallery entry, a study session). Its request
-- stays as history, marked closed (shown as 취소됨), unless another seminar
-- still stands on it. Returns the asset keys the caller may clean up.
--   p = { id }
create or replace function flow_delete_seminar(p jsonb) returns jsonb
language plpgsql set search_path = public as $$
declare
  v_id       text := p ->> 'id';
  v_seminars jsonb;
  v_sem      jsonb;
  v_hidden   boolean;
  v_act      text;
  v_events   jsonb;
  v_session  jsonb;
  v_sessions text[] := '{}';
  v_requests jsonb;
  v_request  jsonb;
  v_req_id   text;
  v_assets   jsonb;
  v_touched  text[] := array['seminars'];
begin
  perform app_lock(array['activities', 'events', 'gallery-dinner',
                         'seminar-requests', 'seminars']);
  v_seminars := app_rows('seminars');
  v_sem := app_find(v_seminars, v_id);
  if v_sem is null then raise exception 'NOT_FOUND'; end if;

  -- Rows written before publicationStatus existed are published (§ migration).
  v_hidden := coalesce(v_sem ->> 'publicationStatus', 'published') <> 'published';
  v_act := v_sem ->> 'activityId';
  v_assets := coalesce(v_sem -> 'materials', '[]') || coalesce(v_sem -> 'photos', '[]')
              || jsonb_build_array(coalesce(v_sem ->> 'posterKey', ''));

  if v_hidden and v_act is not null then
    v_events := app_rows('events');
    if exists (select 1 from jsonb_array_elements(v_seminars) s
                where s ->> 'id' <> v_id and s ->> 'activityId' = v_act)
       or exists (select 1 from jsonb_array_elements(app_rows('gallery-dinner')) g
                   where g ->> 'activityId' = v_act)
       or exists (select 1 from jsonb_array_elements(v_events) e
                   where e ->> 'activityId' = v_act and e ->> 'studyId' is not null)
    then
      raise exception 'CONFLICT';
    end if;
    -- credit beyond the presenters' own (stamped automatically at publication)
    if exists (
      select 1
        from jsonb_array_elements(app_rows('activities')) a,
             jsonb_array_elements_text(a -> 'attendeeIds') as who
       where a ->> 'id' = v_act
         and not (coalesce(v_sem -> 'presenterIds', '[]') ? who)
    ) then
      raise exception 'CONFLICT';
    end if;
    for v_session in
      select e from jsonb_array_elements(v_events) e where e ->> 'activityId' = v_act
    loop
      v_sessions := v_sessions || (v_session ->> 'id');
    end loop;
    perform app_queue_lock(v_sessions);
    if exists (
      select 1 from unnest(v_sessions) as sid,
                    jsonb_array_elements(app_queue_rows(sid)) q
       where q ->> 'status' <> 'rejected'
    ) then
      raise exception 'CONFLICT';
    end if;
    perform app_queue_delete(sid) from unnest(v_sessions) as sid;
    perform app_put('events', app_without(v_events, 'activityId', v_act));
    perform app_put('activities', app_without(app_rows('activities'), 'id', v_act));
    v_touched := v_touched || array['events', 'activities'];
  end if;

  perform app_put('seminars', app_without(v_seminars, 'id', v_id));

  v_req_id := v_sem ->> 'sourceRequestId';
  if v_hidden and v_req_id is not null
     and not exists (select 1 from jsonb_array_elements(v_seminars) s
                      where s ->> 'id' <> v_id and s ->> 'sourceRequestId' = v_req_id)
  then
    v_requests := app_rows('seminar-requests');
    v_request := app_find(v_requests, v_req_id);
    if v_request is not null then
      v_assets := v_assets || jsonb_build_array(coalesce(v_request ->> 'posterKey', ''));
      perform app_put('seminar-requests', app_replace(v_requests, v_req_id,
        v_request || jsonb_build_object('closedAs', 'deleted', 'posterKey', '')));
      v_touched := v_touched || array['seminar-requests'];
    end if;
  end if;

  return jsonb_build_object(
    'touched', to_jsonb(v_touched),
    'touchedQueues', to_jsonb(v_sessions),
    'assets', v_assets);
end $$;

-- Publish a scheduled seminar (admin): flip it to published (deriving its
-- term from the schedule), create its activity and attendance event if they
-- do not exist yet (anchored 'seminar:<id>', so a re-run converges), link the
-- activity, and claim the announcement (announcedAt) when none was sent. The
-- caller sends the announcement after the commit only when `claimed`, and
-- releases the claim if sending fails. Re-running on a published seminar
-- fills in whatever is missing.
--   p = { id, now, activityId, eventId, pathId, attendCode }
--       (ids/tokens for rows that may need creating; now = KST ISO)
create or replace function flow_publish_seminar(p jsonb) returns jsonb
language plpgsql set search_path = public as $$
declare
  v_id       text := p ->> 'id';
  v_anchor   text := 'seminar:' || (p ->> 'id');
  v_seminars jsonb;
  v_sem      jsonb;
  v_sched    jsonb;
  v_date     jsonb;
  v_acts     jsonb;
  v_act      jsonb;
  v_events   jsonb;
  v_event    jsonb;
  v_claimed  boolean := false;
  v_touched  text[] := array['seminars'];
begin
  perform app_lock(array['activities', 'events', 'seminars']);
  v_seminars := app_rows('seminars');
  v_sem := app_find(v_seminars, v_id);
  if v_sem is null then raise exception 'NOT_FOUND'; end if;
  v_sched := app_nullable(v_sem -> 'schedule');
  -- a legacy published row that lost its schedule cannot be published again
  if app_seminar_status(v_sem) not in ('scheduled', 'published') or v_sched is null then
    raise exception 'CONFLICT';
  end if;

  if app_seminar_status(v_sem) = 'scheduled' then
    v_sem := v_sem || jsonb_build_object(
      'publicationStatus', 'published',
      'semester', case when app_may_derive_semester(v_sem)
                       then app_term_of(v_sched ->> 'startsAt')
                       else v_sem ->> 'semester' end);
  end if;
  v_date := jsonb_build_object(
    'start', v_sched -> 'startsAt',
    'end', coalesce(v_sched -> 'endsAt', 'null'::jsonb));

  v_acts := app_rows('activities');
  select a into v_act from jsonb_array_elements(v_acts) a
   where a ->> 'sourceRequestId' = v_anchor limit 1;
  if v_act is null then
    -- presenters are participants of their own seminar
    v_act := jsonb_build_object(
      'id', p ->> 'activityId',
      'title', v_sem ->> 'title',
      'date', v_date,
      'type', '세미나',
      'attendeeIds', coalesce(v_sem -> 'presenterIds', '[]'::jsonb),
      'sourceRequestId', v_anchor);
    perform app_put('activities', v_acts || jsonb_build_array(v_act));
    v_touched := v_touched || array['activities'];
  end if;

  v_events := app_rows('events');
  select e into v_event from jsonb_array_elements(v_events) e
   where e ->> 'sourceRequestId' = v_anchor limit 1;
  if v_event is null then
    v_event := jsonb_build_object(
      'id', p ->> 'eventId',
      'title', v_sem ->> 'title',
      'date', v_date,
      'type', '세미나',
      'status', 'active',
      'pathId', p ->> 'pathId',
      'attendCode', p ->> 'attendCode',
      'activityId', v_act ->> 'id',
      'applicantIds', '[]'::jsonb,
      'presenterIds', coalesce(v_sem -> 'presenterIds', '[]'::jsonb),
      'studyId', null,
      'sessionNo', null,
      'autoGenerated', false,
      'sourceRequestId', v_anchor);
    perform app_put('events', v_events || jsonb_build_array(v_event));
    v_touched := v_touched || array['events'];
  end if;

  v_sem := v_sem || jsonb_build_object('activityId', v_act ->> 'id');
  if v_sem ->> 'announcedAt' is null then
    v_sem := v_sem || jsonb_build_object('announcedAt', p ->> 'now');
    v_claimed := true;
  end if;
  perform app_put('seminars', app_replace(v_seminars, v_id, v_sem));

  return jsonb_build_object(
    'touched', to_jsonb(v_touched),
    'seminar', v_sem,
    'activityId', v_act ->> 'id',
    'eventId', v_event ->> 'id',
    'claimed', v_claimed);
end $$;

-- Change a seminar's schedule (admin). Before publication only the seminar
-- row holds it; after, the same dates also live on its activity and
-- attendance event, and all three change together. A published seminar's
-- term follows the new date unless pinned. Also the way to give a legacy
-- published row (schedule lost in migration) its schedule back.
--   p = { id, schedule }  → { seminar, changed }
create or replace function flow_update_seminar_schedule(p jsonb) returns jsonb
language plpgsql set search_path = public as $$
declare
  v_id       text := p ->> 'id';
  v_new      jsonb := p -> 'schedule';
  v_seminars jsonb;
  v_sem      jsonb;
  v_old      jsonb;
  v_status   text;
  v_changed  boolean;
  v_date     jsonb;
  v_touched  text[] := array['seminars'];
begin
  perform app_lock(array['activities', 'events', 'seminars']);
  v_seminars := app_rows('seminars');
  v_sem := app_find(v_seminars, v_id);
  if v_sem is null then raise exception 'NOT_FOUND'; end if;
  v_status := app_seminar_status(v_sem);
  if v_status in ('cancelled', 'unscheduled') then raise exception 'CONFLICT'; end if;

  v_old := app_nullable(v_sem -> 'schedule');
  v_changed := v_old is null
    or v_old ->> 'startsAt' is distinct from v_new ->> 'startsAt'
    or v_old ->> 'endsAt' is distinct from v_new ->> 'endsAt'
    or v_old ->> 'location' is distinct from v_new ->> 'location';
  v_sem := v_sem || jsonb_build_object(
    'schedule', v_new,
    'semester', case when v_status = 'published' and app_may_derive_semester(v_sem)
                     then app_term_of(v_new ->> 'startsAt')
                     else v_sem ->> 'semester' end);
  perform app_put('seminars', app_replace(v_seminars, v_id, v_sem));

  if v_status = 'published' then
    v_date := jsonb_build_object(
      'start', v_new -> 'startsAt',
      'end', coalesce(v_new -> 'endsAt', 'null'::jsonb));
    perform app_put('activities', (
      select coalesce(jsonb_agg(
               case when a ->> 'id' = v_sem ->> 'activityId'
                      or a ->> 'sourceRequestId' = 'seminar:' || v_id
                    then a || jsonb_build_object('date', v_date) else a end
               order by n), '[]'::jsonb)
        from jsonb_array_elements(app_rows('activities')) with ordinality as x(a, n)));
    perform app_put('events', (
      select coalesce(jsonb_agg(
               case when app_is_seminar_event(e, v_sem)
                    then e || jsonb_build_object('date', v_date) else e end
               order by n), '[]'::jsonb)
        from jsonb_array_elements(app_rows('events')) with ordinality as x(e, n)));
    v_touched := v_touched || array['activities', 'events'];
  end if;

  return jsonb_build_object(
    'touched', to_jsonb(v_touched),
    'seminar', v_sem,
    'changed', v_changed);
end $$;

-- Cancel a seminar and its attendance events (presenter or admin). A
-- presenter may cancel only their own seminar and only before it starts; an
-- admin may cancel a started one with `acknowledgeStarted`. Activities and
-- attendance are kept (the read side hides them). Idempotent. "Started" is
-- the schedule's start, or — for a legacy published row without one —
-- "already held".
--   p = { id, memberId, isAdmin, acknowledgeStarted, now }
--   → { seminar, flipped, wasAnnounced, started }
create or replace function flow_cancel_seminar(p jsonb) returns jsonb
language plpgsql set search_path = public as $$
declare
  v_id        text := p ->> 'id';
  v_is_admin  boolean := coalesce((p ->> 'isAdmin')::boolean, false);
  v_seminars  jsonb;
  v_sem       jsonb;
  v_sched     jsonb;
  v_status    text;
  v_started   boolean;
  v_flipped   boolean := false;
  v_announced boolean := false;
  v_events    jsonb;
  v_next      jsonb;
  v_touched   text[] := '{}';
begin
  perform app_lock(array['events', 'seminars']);
  v_seminars := app_rows('seminars');
  v_sem := app_find(v_seminars, v_id);
  if v_sem is null then raise exception 'NOT_FOUND'; end if;
  v_status := app_seminar_status(v_sem);
  v_sched := app_nullable(v_sem -> 'schedule');
  v_started := case when v_sched is not null
                    then (v_sched ->> 'startsAt')::timestamptz <= (p ->> 'now')::timestamptz
                    else v_status = 'published' end;

  if not v_is_admin then
    if not (coalesce(v_sem -> 'presenterIds', '[]'::jsonb) ? (p ->> 'memberId'))
       or v_started then
      raise exception 'FORBIDDEN';
    end if;
  elsif v_started and not coalesce((p ->> 'acknowledgeStarted')::boolean, false) then
    raise exception 'CONFLICT';
  end if;

  if v_status <> 'cancelled' then
    v_announced := v_status = 'published' and v_sem ->> 'announcedAt' is not null;
    v_sem := v_sem || jsonb_build_object('publicationStatus', 'cancelled');
    perform app_put('seminars', app_replace(v_seminars, v_id, v_sem));
    v_touched := v_touched || array['seminars'];
    v_flipped := true;
  end if;

  v_events := app_rows('events');
  select coalesce(jsonb_agg(
           case when app_is_seminar_event(e, v_sem) and e ->> 'status' <> 'cancelled'
                then e || jsonb_build_object('status', 'cancelled') else e end
           order by n), '[]'::jsonb)
    into v_next
    from jsonb_array_elements(v_events) with ordinality as x(e, n);
  if v_next <> v_events then
    perform app_put('events', v_next);
    v_touched := v_touched || array['events'];
  end if;

  return jsonb_build_object(
    'touched', to_jsonb(v_touched),
    'seminar', v_sem,
    'flipped', v_flipped,
    'wasAnnounced', v_announced,
    'started', v_started);
end $$;

-- Check in to an event (member): a pending row in the event's queue. The
-- event is read under a SHARE lock — check-ins do not wait for each other,
-- but a delete or cancel of the event cannot commit in between, so no row is
-- ever queued for an event that is gone or closed.
--   p = { eventId, memberId, id, now }  (id = new row id, now = KST ISO)
create or replace function flow_check_in(p jsonb) returns jsonb
language plpgsql set search_path = public as $$
declare
  v_event_id text := p ->> 'eventId';
  v_member   text := p ->> 'memberId';
  v_event    jsonb;
  v_rows     jsonb;
  v_record   jsonb;
begin
  perform 1 from app_tables where name = 'events' for share;
  v_event := app_find(app_rows('events'), v_event_id);
  if v_event is null then raise exception 'NOT_FOUND'; end if;
  if not app_event_open(v_event, (p ->> 'now')::timestamptz) then
    raise exception 'EVENT_NOT_OPEN';
  end if;

  insert into app_queues (event_id, version, doc)
    values (v_event_id, 1, jsonb_build_object('schemaVersion', 1, 'rows', '[]'::jsonb))
    on conflict (event_id) do nothing;
  perform app_queue_lock(array[v_event_id]);
  v_rows := app_queue_rows(v_event_id);
  if exists (select 1 from jsonb_array_elements(v_rows) r where r ->> 'memberId' = v_member) then
    raise exception 'CONFLICT';
  end if;
  -- one-click completion records both instants
  v_record := jsonb_build_object(
    'id', p ->> 'id',
    'memberId', v_member,
    'eventId', v_event_id,
    'startTime', p ->> 'now',
    'endTime', p ->> 'now',
    'status', 'pending');
  perform app_queue_put(v_event_id, v_rows || jsonb_build_array(v_record));

  return jsonb_build_object(
    'touchedQueues', jsonb_build_array(v_event_id),
    'record', v_record);
end $$;

-- Decide a check-in (admin): approve credits the member on the event's
-- activity; reject or delete of an APPROVED row takes that credit back
-- (API-SPEC §7-2). Queue row and activity change together, so an approve and
-- a reject racing on one row cannot leave a rejected row with credit.
--   p = { eventId, queueId, decision: 'approve' | 'reject' | 'delete' }
create or replace function flow_decide_attendance(p jsonb) returns jsonb
language plpgsql set search_path = public as $$
declare
  v_event_id text := p ->> 'eventId';
  v_queue_id text := p ->> 'queueId';
  v_decision text := p ->> 'decision';
  v_rows     jsonb;
  v_row      jsonb;
  v_member   text;
  v_event    jsonb;
  v_acts     jsonb;
  v_act      jsonb;
  v_touched  text[] := '{}';
begin
  if v_decision not in ('approve', 'reject', 'delete') then
    raise exception 'VALIDATION_FAILED';
  end if;
  perform app_lock(array['activities', 'events']);
  perform app_queue_lock(array[v_event_id]);
  v_rows := app_queue_rows(v_event_id);
  v_row := app_find(v_rows, v_queue_id);
  if v_row is null then raise exception 'NOT_FOUND'; end if;
  v_member := v_row ->> 'memberId';
  v_event := app_find(app_rows('events'), v_event_id);
  v_acts := app_rows('activities');

  if v_decision = 'approve' then
    if v_event is null then raise exception 'NOT_FOUND'; end if;
    v_act := app_find(v_acts, v_event ->> 'activityId');
    if v_act is null then raise exception 'NOT_FOUND'; end if; -- dangling reference
    if not (v_act -> 'attendeeIds' ? v_member) then
      perform app_put('activities', app_replace(v_acts, v_act ->> 'id',
        jsonb_set(v_act, '{attendeeIds}', (v_act -> 'attendeeIds') || to_jsonb(v_member))));
      v_touched := v_touched || array['activities'];
    end if;
    perform app_queue_put(v_event_id, app_replace(v_rows, v_queue_id,
      v_row || jsonb_build_object('status', 'approved')));
  else
    if v_row ->> 'status' = 'approved' and v_event is not null then
      v_act := app_find(v_acts, v_event ->> 'activityId');
      if v_act is not null and v_act -> 'attendeeIds' ? v_member then
        perform app_put('activities', app_replace(v_acts, v_act ->> 'id',
          jsonb_set(v_act, '{attendeeIds}', (v_act -> 'attendeeIds') - v_member)));
        v_touched := v_touched || array['activities'];
      end if;
    end if;
    if v_decision = 'reject' then
      perform app_queue_put(v_event_id, app_replace(v_rows, v_queue_id,
        v_row || jsonb_build_object('status', 'rejected')));
    else
      perform app_queue_put(v_event_id, app_without(v_rows, 'id', v_queue_id));
    end if;
  end if;

  return jsonb_build_object(
    'touched', to_jsonb(v_touched),
    'touchedQueues', jsonb_build_array(v_event_id));
end $$;

-- Delete an event (admin) with its queue — refused while check-ins are still
-- pending (API-SPEC §7-2). The event lock keeps a check-in from landing
-- between the pending test and the delete.
--   p = { id }
create or replace function flow_delete_event(p jsonb) returns jsonb
language plpgsql set search_path = public as $$
declare
  v_id     text := p ->> 'id';
  v_events jsonb;
begin
  perform app_lock(array['events']);
  perform app_queue_lock(array[v_id]);
  if exists (select 1 from jsonb_array_elements(app_queue_rows(v_id)) q
              where q ->> 'status' = 'pending') then
    raise exception 'CONFLICT';
  end if;
  v_events := app_rows('events');
  if app_find(v_events, v_id) is null then raise exception 'NOT_FOUND'; end if;
  perform app_put('events', app_without(v_events, 'id', v_id));
  perform app_queue_delete(v_id);
  return jsonb_build_object(
    'touched', jsonb_build_array('events'),
    'touchedQueues', jsonb_build_array(v_id));
end $$;

-- Approve a membership application (admin) — S9 conversion. A new applicant
-- becomes a member + private-info (inheriting join date, roles and project
-- from a legacy record with the same email); a returning one keeps their rows
-- and gets the application's contact details. Either way: this term's
-- registration, then the application row is removed. All or nothing, on the
-- application as it is now — an approve racing a reject either wins whole or
-- finds the row gone, never leaving a member behind a rejected application.
-- Steps anchored on the application id (sourceRequestId) are not repeated.
--   p = { id, now, today, term, adminEmailHashes[],
--         memberId, privateInfoId, registrationId }   (ids for new rows)
--   → { name, email, memberId }
create or replace function flow_approve_application(p jsonb) returns jsonb
language plpgsql set search_path = public as $$
declare
  v_id        text := p ->> 'id';
  v_apps      jsonb;
  v_app       jsonb;
  v_email     text;
  v_admin     boolean;
  v_members   jsonb;
  v_member    jsonb;
  v_infos     jsonb;
  v_info      jsonb;
  v_lp_info   jsonb;
  v_lp_member jsonb;
  v_member_id text;
  v_regs      jsonb;
  v_touched   text[] := array['applications'];
begin
  perform app_lock(array['applications', 'members', 'private-info', 'registrations']);
  v_apps := app_rows('applications');
  v_app := app_find(v_apps, v_id);
  if v_app is null then
    -- gone: converted already (its registration exists) or never there
    if exists (select 1 from jsonb_array_elements(app_rows('registrations')) r
                where r ->> 'sourceRequestId' = v_id) then
      raise exception 'CONFLICT';
    end if;
    raise exception 'NOT_FOUND';
  end if;

  v_email := lower(trim(v_app ->> 'email'));
  -- bootstrap admins are stamped on conversion; the record is the truth after
  -- (sha256 hex of normalized emails: the addresses stay out of RPC arguments)
  v_admin := coalesce(p -> 'adminEmailHashes', '[]'::jsonb)
             ? encode(sha256(convert_to(v_email, 'UTF8')), 'hex');
  v_members := app_rows('members');
  v_infos := app_rows('private-info');
  select i into v_info from jsonb_array_elements(v_infos) i
   where lower(trim(i ->> 'email')) = v_email limit 1;

  if v_info is not null then
    -- returning member: refresh contact details from the application
    v_member_id := v_info ->> 'memberId';
    if v_admin then
      v_member := app_find(v_members, v_member_id);
      if v_member is not null and not coalesce((v_member ->> 'isAdmin')::boolean, false) then
        perform app_put('members', app_replace(v_members, v_member_id,
          v_member || jsonb_build_object('isAdmin', true)));
        v_touched := v_touched || array['members'];
      end if;
    end if;
    perform app_put('private-info', app_replace(v_infos, v_info ->> 'id',
      v_info || jsonb_build_object(
        'phone', v_app -> 'phone',
        'studentId', coalesce(nullif(v_app ->> 'studentId', ''), v_info ->> 'studentId', ''),
        'background', v_app -> 'background')));
    v_touched := v_touched || array['private-info'];
  else
    -- new member. Continuity fields come from the legacy archive (join date,
    -- officer history, project); status, alumni flags and publicContact do
    -- not (charter reclassification, consent re-check).
    select i into v_lp_info from jsonb_array_elements(app_rows('legacy-private-info')) i
     where lower(trim(i ->> 'email')) = v_email limit 1;
    if v_lp_info is not null then
      v_lp_member := app_find(app_rows('legacy-members'), v_lp_info ->> 'memberId');
    end if;

    select m into v_member from jsonb_array_elements(v_members) m
     where m ->> 'sourceRequestId' = v_id limit 1;
    if v_member is null then
      v_member := jsonb_build_object(
        'id', p ->> 'memberId',
        'name', v_app -> 'name',
        'department', v_app -> 'department',
        'joinedAt', coalesce(app_nullable(v_lp_member -> 'joinedAt'), to_jsonb(p ->> 'today')),
        'status', 'associate',
        'statusChangedAt', p ->> 'now',
        'withdrawal', null,
        'isAlumni', false,
        'alumniRevoked', false,
        'roles', coalesce(v_lp_member -> 'roles', '[]'::jsonb),
        'isAdmin', v_admin,
        'publicContact', null,
        'project', coalesce(v_lp_member -> 'project', 'null'::jsonb),
        'legacyMemberId', coalesce(v_lp_info -> 'memberId', 'null'::jsonb),
        'sourceRequestId', v_id);
      perform app_put('members', v_members || jsonb_build_array(v_member));
      v_touched := v_touched || array['members'];
    end if;
    v_member_id := v_member ->> 'id';

    if not exists (select 1 from jsonb_array_elements(v_infos) i
                    where i ->> 'sourceRequestId' = v_id) then
      perform app_put('private-info', v_infos || jsonb_build_array(jsonb_build_object(
        'id', p ->> 'privateInfoId',
        'memberId', v_member_id,
        'email', v_app -> 'email',
        'phone', v_app -> 'phone',
        'studentId', coalesce(v_app -> 'studentId', '""'::jsonb),
        'background', v_app -> 'background',
        'mailPrefs', jsonb_build_object('announcements', true),
        'hidePublicPhone', false,
        'sourceRequestId', v_id)));
      v_touched := v_touched || array['private-info'];
    end if;
  end if;

  -- S9: this term's registration — the source of every membership right
  v_regs := app_rows('registrations');
  if not exists (select 1 from jsonb_array_elements(v_regs) r
                  where r ->> 'sourceRequestId' = v_id) then
    perform app_put('registrations', v_regs || jsonb_build_array(jsonb_build_object(
      'id', p ->> 'registrationId',
      'memberId', v_member_id,
      'term', p ->> 'term',
      'registeredAt', p ->> 'now',
      'sourceRequestId', v_id)));
    v_touched := v_touched || array['registrations'];
  end if;

  perform app_put('applications', app_without(v_apps, 'id', v_id));

  return jsonb_build_object(
    'touched', to_jsonb(v_touched),
    'name', v_app ->> 'name',
    'email', v_app ->> 'email',
    'memberId', v_member_id);
end $$;

-- Approve a seminar request (admin): the archive record (unscheduled — the
-- schedule is agreed afterwards) and the request's flip to approved, together
-- and on the request as it is now: a request withdrawn, rejected or edited
-- since the admin's page load is judged by its current state. The request's
-- poster moves to the seminar. A seminar already anchored on the request (a
-- run cut short before this function existed) is reused.
--   p = { id, seminarId, term }  → { request }  (as it was before the flip)
create or replace function flow_approve_seminar_request(p jsonb) returns jsonb
language plpgsql set search_path = public as $$
declare
  v_id       text := p ->> 'id';
  v_requests jsonb;
  v_req      jsonb;
  v_seminars jsonb;
  v_touched  text[] := array['seminar-requests'];
begin
  perform app_lock(array['seminar-requests', 'seminars']);
  v_requests := app_rows('seminar-requests');
  v_req := app_find(v_requests, v_id);
  if v_req is null then raise exception 'NOT_FOUND'; end if;
  if v_req ->> 'status' <> 'pending' then raise exception 'CONFLICT'; end if;

  v_seminars := app_rows('seminars');
  if not exists (select 1 from jsonb_array_elements(v_seminars) s
                  where s ->> 'sourceRequestId' = v_id) then
    perform app_put('seminars', v_seminars || jsonb_build_array(jsonb_build_object(
      'id', p ->> 'seminarId',
      'title', v_req -> 'title',
      -- provisional: publication derives the term from the real schedule
      'semester', p ->> 'term',
      'note', v_req -> 'description',
      'description', v_req -> 'description',
      'presenterIds', coalesce(v_req -> 'presenterIds', '[]'::jsonb),
      'externalPresenters', '',
      'materials', '[]'::jsonb,
      'photos', '[]'::jsonb,
      'posterKey', coalesce(v_req -> 'posterKey', '""'::jsonb),
      'preferredTiming', coalesce(v_req -> 'preferredTiming', '""'::jsonb),
      'publicationStatus', 'unscheduled',
      'schedule', null,
      'announcedAt', null,
      'semesterPinned', false,
      'activityId', null,
      'sourceRequestId', v_id)));
    v_touched := v_touched || array['seminars'];
  end if;

  perform app_put('seminar-requests', app_replace(v_requests, v_id,
    v_req || jsonb_build_object('status', 'approved')));
  return jsonb_build_object('touched', to_jsonb(v_touched), 'request', v_req);
end $$;

-- Approve a study request (admin, ADM-16): the study with the requester as
-- organizer and first participant, and the request's flip to approved —
-- together, on the request as it is now. An anchored study is reused.
--   p = { id, studyId }  → { request }  (as it was before the flip)
create or replace function flow_approve_study_request(p jsonb) returns jsonb
language plpgsql set search_path = public as $$
declare
  v_id       text := p ->> 'id';
  v_requests jsonb;
  v_req      jsonb;
  v_studies  jsonb;
  v_touched  text[] := array['study-requests'];
begin
  perform app_lock(array['studies', 'study-requests']);
  v_requests := app_rows('study-requests');
  v_req := app_find(v_requests, v_id);
  if v_req is null then raise exception 'NOT_FOUND'; end if;
  if v_req ->> 'status' <> 'pending' then raise exception 'CONFLICT'; end if;

  v_studies := app_rows('studies');
  if not exists (select 1 from jsonb_array_elements(v_studies) s
                  where s ->> 'sourceRequestId' = v_id) then
    perform app_put('studies', v_studies || jsonb_build_array(jsonb_build_object(
      'id', p ->> 'studyId',
      'title', v_req -> 'title',
      'semester', v_req -> 'semester',
      'textbook', v_req -> 'textbook',
      'description', v_req -> 'description',
      'note', '',
      'organizerIds', jsonb_build_array(v_req -> 'requesterId'),
      'participantIds', jsonb_build_array(v_req -> 'requesterId'),
      'pendingParticipantIds', '[]'::jsonb,
      'pendingTransfer', null,
      'schedule', '[]'::jsonb,
      'transferHistory', '[]'::jsonb,
      'photos', '[]'::jsonb,
      'status', 'recruiting',
      'sourceRequestId', v_id)));
    v_touched := v_touched || array['studies'];
  end if;

  perform app_put('study-requests', app_replace(v_requests, v_id,
    v_req || jsonb_build_object('status', 'approved')));
  return jsonb_build_object('touched', to_jsonb(v_touched), 'request', v_req);
end $$;

-- Create one study session (organizer): the activity + attendance event pair,
-- anchored on '<studyId>:<date>' so a repeated click returns the same
-- session. The session number is taken under the events lock, so two
-- sessions created at once never share one. A cancelled session keeps its
-- slot forever (review M2): refused with DETAIL 'session-slot-cancelled'.
--   p = { studyId, date, title, autoGenerated,
--         activityId, eventId, pathId, attendCode }  → { event }
create or replace function flow_create_study_session(p jsonb) returns jsonb
language plpgsql set search_path = public as $$
declare
  v_study_id text := p ->> 'studyId';
  v_key      text := (p ->> 'studyId') || ':' || (p ->> 'date');
  v_study    jsonb;
  v_events   jsonb;
  v_event    jsonb;
  v_acts     jsonb;
  v_act      jsonb;
  v_no       int;
  v_title    text;
  v_touched  text[] := '{}';
begin
  perform app_lock(array['activities', 'events', 'studies']);
  v_study := app_find(app_rows('studies'), v_study_id);
  if v_study is null then raise exception 'NOT_FOUND'; end if;
  if v_study ->> 'status' = 'finished' then raise exception 'CONFLICT'; end if;

  v_events := app_rows('events');
  select e into v_event from jsonb_array_elements(v_events) e
   where e ->> 'sourceRequestId' = v_key limit 1;
  if v_event is not null and v_event ->> 'status' = 'cancelled' then
    raise exception 'CONFLICT' using detail = 'session-slot-cancelled';
  end if;
  if v_event is not null then
    return jsonb_build_object('touched', '[]'::jsonb, 'event', v_event);
  end if;

  select coalesce(max((e ->> 'sessionNo')::int), 0) + 1 into v_no
    from jsonb_array_elements(v_events) e
   where e ->> 'studyId' = v_study_id;
  v_title := coalesce(nullif(p ->> 'title', ''), (v_study ->> 'title') || ' ' || v_no || '회차');

  v_acts := app_rows('activities');
  select a into v_act from jsonb_array_elements(v_acts) a
   where a ->> 'sourceRequestId' = v_key limit 1;
  if v_act is null then
    v_act := jsonb_build_object(
      'id', p ->> 'activityId',
      'title', v_title,
      'date', jsonb_build_object('start', p ->> 'date', 'end', null),
      'type', '스터디',
      'attendeeIds', '[]'::jsonb,
      'sourceRequestId', v_key);
    perform app_put('activities', v_acts || jsonb_build_array(v_act));
    v_touched := v_touched || array['activities'];
  end if;

  v_event := jsonb_build_object(
    'id', p ->> 'eventId',
    'title', v_title,
    'date', jsonb_build_object('start', p ->> 'date', 'end', null),
    'type', '스터디',
    'status', 'active',
    'pathId', p ->> 'pathId',
    'attendCode', p ->> 'attendCode',
    'activityId', v_act ->> 'id',
    'applicantIds', '[]'::jsonb,
    'presenterIds', '[]'::jsonb,
    'studyId', v_study_id,
    'sessionNo', v_no,
    'autoGenerated', coalesce((p ->> 'autoGenerated')::boolean, false),
    'sourceRequestId', v_key);
  perform app_put('events', v_events || jsonb_build_array(v_event));
  v_touched := v_touched || array['events'];

  return jsonb_build_object('touched', to_jsonb(v_touched), 'event', v_event);
end $$;

-- Correct a study session (organizer): title and/or start move on the event
-- and on its activity together — archives and term grouping key off the
-- activity's date (review M5). The anchor keeps the ORIGINAL date on
-- purpose: the old slot stays consumed. Empty title/date = keep.
--   p = { studyId, eventId, title, date }
create or replace function flow_update_study_session(p jsonb) returns jsonb
language plpgsql set search_path = public as $$
declare
  v_events jsonb;
  v_event  jsonb;
  v_acts   jsonb;
  v_act    jsonb;
  v_title  text := nullif(p ->> 'title', '');
  v_date   jsonb := case when coalesce(p ->> 'date', '') = '' then null
                         else jsonb_build_object('start', p ->> 'date', 'end', null) end;
begin
  perform app_lock(array['activities', 'events']);
  v_events := app_rows('events');
  select e into v_event from jsonb_array_elements(v_events) e
   where e ->> 'id' = p ->> 'eventId' and e ->> 'studyId' = p ->> 'studyId' limit 1;
  if v_event is null then raise exception 'NOT_FOUND'; end if;

  perform app_put('events', app_replace(v_events, v_event ->> 'id',
    v_event || jsonb_build_object(
      'title', coalesce(v_title, v_event ->> 'title'),
      'date', coalesce(v_date, v_event -> 'date'))));

  v_acts := app_rows('activities');
  v_act := app_find(v_acts, v_event ->> 'activityId');
  if v_act is not null then
    perform app_put('activities', app_replace(v_acts, v_act ->> 'id',
      v_act || jsonb_build_object(
        'title', coalesce(v_title, v_act ->> 'title'),
        'date', coalesce(v_date, v_act -> 'date'))));
  end if;
  return jsonb_build_object('touched', jsonb_build_array('activities', 'events'));
end $$;

-- Append one audit row (API-SPEC §1-5) inside the caller's transaction — for
-- withdrawal-lifecycle entries, which are destruction evidence: the change
-- and its record commit together or not at all.
create or replace function app_audit(p_id text, p_at text, p_actor text, p_action text,
                                     p_target_tb text, p_target_id text)
returns void language sql set search_path = public as $$
  insert into audit_log (id, at, actor, action, target_tb, target_id, detail)
  values (p_id, p_at::timestamptz, p_actor, p_action, p_target_tb, p_target_id, null)
$$;

-- A member's own withdrawal request (MEM-07, API-SPEC §4-7). The triple
-- confirmation is checked here on the member as stored; an organizer of an
-- unfinished study must hand over first — read under a share lock, so a
-- handover accepted meanwhile cannot slip past. The status change and its
-- audit row commit together.
--   p = { memberId, ackInfo, ackDataPolicy, confirmName (trimmed), now,
--         auditId, auditAt }
create or replace function flow_request_withdrawal(p jsonb) returns jsonb
language plpgsql set search_path = public as $$
declare
  v_id      text := p ->> 'memberId';
  v_members jsonb;
  v_m       jsonb;
begin
  perform app_lock(array['members']);
  perform 1 from app_tables where name = 'studies' for share;
  v_members := app_rows('members');
  v_m := app_find(v_members, v_id);
  if v_m is null then raise exception 'NOT_FOUND'; end if;
  if v_m ->> 'status' = 'withdrawn' then raise exception 'CONFLICT'; end if;
  if not coalesce((p ->> 'ackInfo')::boolean, false)
     or not coalesce((p ->> 'ackDataPolicy')::boolean, false)
     or p ->> 'confirmName' is distinct from v_m ->> 'name' then
    raise exception 'VALIDATION_FAILED';
  end if;
  if exists (select 1 from jsonb_array_elements(app_rows('studies')) s
              where s -> 'organizerIds' ? v_id and s ->> 'status' <> 'finished') then
    raise exception 'CONFLICT';
  end if;

  perform app_put('members', app_replace(v_members, v_id, v_m || jsonb_build_object(
    'status', 'withdrawn',
    'statusChangedAt', p ->> 'now',
    'withdrawal', jsonb_build_object(
      'requestedAt', p ->> 'now',
      'previousStatus', v_m ->> 'status',
      'holdBy', null,
      'holdAt', null))));
  perform app_audit(p ->> 'auditId', p ->> 'auditAt', v_id, 'withdrawal.request', 'members', v_id);
  return jsonb_build_object('touched', jsonb_build_array('members'));
end $$;

-- The rest of the withdrawal lifecycle, each with its audit row:
--   cancel  — the member's own; restores the pre-withdrawal status
--   hold    — admin (ADM-17); pauses the grace period
--   release — admin; lifts the hold and restarts the one-month clock
--   p = { memberId, op, actorId, now, auditId, auditAt }
create or replace function flow_member_withdrawal(p jsonb) returns jsonb
language plpgsql set search_path = public as $$
declare
  v_id      text := p ->> 'memberId';
  v_op      text := p ->> 'op';
  v_members jsonb;
  v_m       jsonb;
  v_w       jsonb;
  v_next    jsonb;
begin
  if v_op not in ('cancel', 'hold', 'release') then raise exception 'VALIDATION_FAILED'; end if;
  perform app_lock(array['members']);
  v_members := app_rows('members');
  v_m := app_find(v_members, v_id);
  if v_m is null then raise exception 'NOT_FOUND'; end if;
  v_w := app_nullable(v_m -> 'withdrawal');
  if v_m ->> 'status' <> 'withdrawn' or v_w is null then
    -- nothing to cancel is "not found" for the member; a hold on it is a conflict
    if v_op = 'cancel' then raise exception 'NOT_FOUND'; end if;
    raise exception 'CONFLICT';
  end if;

  if v_op = 'cancel' then
    v_next := v_m || jsonb_build_object(
      'status', v_w ->> 'previousStatus',
      'statusChangedAt', p ->> 'now',
      'withdrawal', null);
  elsif v_op = 'hold' then
    v_next := v_m || jsonb_build_object('withdrawal', v_w || jsonb_build_object(
      'holdBy', p ->> 'actorId', 'holdAt', p ->> 'now'));
  else
    if app_nullable(v_w -> 'holdBy') is null then raise exception 'CONFLICT'; end if;
    v_next := v_m || jsonb_build_object('withdrawal', v_w || jsonb_build_object(
      'holdBy', null, 'holdAt', null, 'requestedAt', p ->> 'now'));
  end if;

  perform app_put('members', app_replace(v_members, v_id, v_next));
  perform app_audit(p ->> 'auditId', p ->> 'auditAt', p ->> 'actorId',
    case v_op when 'cancel' then 'withdrawal.cancel'
              when 'hold' then 'withdrawal.hold'
              else 'withdrawal.release-hold' end,
    'members', v_id);
  return jsonb_build_object('touched', jsonb_build_array('members'));
end $$;

-- Delete an activity record (admin record editor) — refused while an event,
-- a gallery entry or a seminar points at it; the check and the delete share
-- one lock, so a reference added meanwhile cannot be orphaned.
--   p = { id }
create or replace function flow_delete_activity(p jsonb) returns jsonb
language plpgsql set search_path = public as $$
declare
  v_id   text := p ->> 'id';
  v_acts jsonb;
begin
  perform app_lock(array['activities', 'events', 'gallery-dinner', 'seminars']);
  if exists (select 1 from jsonb_array_elements(app_rows('events')) e where e ->> 'activityId' = v_id)
     or exists (select 1 from jsonb_array_elements(app_rows('gallery-dinner')) g where g ->> 'activityId' = v_id)
     or exists (select 1 from jsonb_array_elements(app_rows('seminars')) s where s ->> 'activityId' = v_id)
  then
    raise exception 'CONFLICT';
  end if;
  v_acts := app_rows('activities');
  if app_find(v_acts, v_id) is null then raise exception 'NOT_FOUND'; end if;
  perform app_put('activities', app_without(v_acts, 'id', v_id));
  return jsonb_build_object('touched', jsonb_build_array('activities'));
end $$;

-- Delete a study record (admin record editor) — refused while it has
-- sessions. Returns its photo keys for cleanup after the commit.
--   p = { id }  → { assets }
create or replace function flow_delete_study(p jsonb) returns jsonb
language plpgsql set search_path = public as $$
declare
  v_id      text := p ->> 'id';
  v_studies jsonb;
  v_study   jsonb;
begin
  perform app_lock(array['events', 'studies']);
  if exists (select 1 from jsonb_array_elements(app_rows('events')) e where e ->> 'studyId' = v_id) then
    raise exception 'CONFLICT';
  end if;
  v_studies := app_rows('studies');
  v_study := app_find(v_studies, v_id);
  if v_study is null then raise exception 'NOT_FOUND'; end if;
  perform app_put('studies', app_without(v_studies, 'id', v_id));
  return jsonb_build_object(
    'touched', jsonb_build_array('studies'),
    'assets', coalesce(v_study -> 'photos', '[]'::jsonb));
end $$;

-- ---------------------------------------------------------------------------
-- 99. Privileges — flows and helpers run for the service role only.
--     (Guarded: PGlite has no Supabase roles.)
-- ---------------------------------------------------------------------------

do $$
declare
  f record;
  has_roles boolean := exists (select 1 from pg_roles where rolname = 'service_role');
begin
  for f in
    select p.oid::regprocedure as sig
      from pg_proc p join pg_namespace n on n.oid = p.pronamespace
     where n.nspname = 'public'
       and (p.proname like 'app\_%' or p.proname like 'flow\_%')
  loop
    execute format('revoke all on function %s from public', f.sig);
    if has_roles then
      execute format('revoke all on function %s from anon, authenticated', f.sig);
      execute format('grant execute on function %s to service_role', f.sig);
    end if;
  end loop;
end $$;
