-- ============================================================================
-- 20260928000000_atomic_flows.sql — multi-document flows as plpgsql functions
--
-- Design : docs/spec/ATOMIC-FLOWS.md (decision 2026-09-27, option B)
-- Run on : BOTH prod and dev, BEFORE deploying code that calls these
--          functions. Expand-only: the currently deployed code ignores them.
--          Idempotent — safe to re-run.
-- Also   : applied in-process by PGlite for tests and DATA_BACKEND=memory
--          (src/lib/server/data/store-memory.ts), so every statement must run
--          on plain Postgres without Supabase roles.
--
-- Conventions
--   * Every flow is `flow_<name>(p jsonb) returns jsonb`; PostgREST calls it as
--     rpc('flow_<name>', { p: {...} }).
--   * Failures RAISE a bare app error code as the message (NOT_FOUND, CONFLICT,
--     VALIDATION_FAILED, EVENT_NOT_OPEN, FORBIDDEN); the whole transaction
--     rolls back. The TS side maps the message to AppError.
--   * ids and timestamps come IN as arguments (generated by TS: ULID, KST ISO)
--     so SQL-written rows have exactly the shapes TS writes.
--   * Returns { "touched": [table names...], ... } — TS invalidates caches of
--     the touched tables.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1. Document helpers
-- ---------------------------------------------------------------------------

-- rows[] of a table document ('[]' when the document does not exist yet)
create or replace function app_rows(p_name text) returns jsonb
language sql stable set search_path = public as $$
  select coalesce(
    (select doc -> 'rows' from app_tables where name = p_name),
    '[]'::jsonb)
$$;

-- Lock table documents for the rest of the transaction, in name order (no
-- deadlocks between flows). Missing documents are created empty first so
-- they can be locked too — readers treat "missing" and "empty" alike.
create or replace function app_lock(p_names text[]) returns void
language plpgsql set search_path = public as $$
begin
  insert into app_tables (name, version, doc)
    select n, 1, jsonb_build_object('schemaVersion', 1, 'rows', '[]'::jsonb)
    from unnest(p_names) as n
    on conflict (name) do nothing;
  perform 1 from app_tables where name = any (p_names) order by name for update;
end $$;

-- Replace a (locked) table document's rows and bump its version — the same
-- version CAS the TS writers use, so a concurrent TS mutate retries.
create or replace function app_put(p_name text, p_rows jsonb) returns void
language plpgsql set search_path = public as $$
begin
  update app_tables
     set doc = jsonb_set(doc, '{rows}', coalesce(p_rows, '[]'::jsonb)),
         version = version + 1
   where name = p_name;
  if not found then
    raise exception 'app_put: % is not locked/created', p_name;
  end if;
end $$;

-- The row with this id, or NULL.
create or replace function app_find(p_rows jsonb, p_id text) returns jsonb
language sql immutable as $$
  select r from jsonb_array_elements(p_rows) as r where r ->> 'id' = p_id limit 1
$$;

-- rows[] without the row(s) matching a predicate key/value.
create or replace function app_without(p_rows jsonb, p_key text, p_value text)
returns jsonb language sql immutable as $$
  select coalesce(jsonb_agg(r), '[]'::jsonb)
    from jsonb_array_elements(p_rows) as r
   where r ->> p_key is distinct from p_value
$$;

-- rows[] with the row of this id replaced by p_row.
create or replace function app_replace(p_rows jsonb, p_id text, p_row jsonb)
returns jsonb language sql immutable as $$
  select coalesce(jsonb_agg(case when r ->> 'id' = p_id then p_row else r end), '[]'::jsonb)
    from jsonb_array_elements(p_rows) as r
$$;

-- Attendance queues live one document per event in app_queues.
create or replace function app_queue_lock(p_event_ids text[]) returns void
language plpgsql set search_path = public as $$
begin
  perform 1 from app_queues where event_id = any (p_event_ids) order by event_id for update;
end $$;

create or replace function app_queue_rows(p_event_id text) returns jsonb
language sql stable set search_path = public as $$
  select coalesce(
    (select doc -> 'rows' from app_queues where event_id = p_event_id),
    '[]'::jsonb)
$$;

create or replace function app_queue_delete(p_event_id text) returns void
language sql set search_path = public as $$
  delete from app_queues where event_id = p_event_id
$$;

-- Replace a (locked) queue document's rows and bump its version.
create or replace function app_queue_put(p_event_id text, p_rows jsonb) returns void
language plpgsql set search_path = public as $$
begin
  update app_queues
     set doc = jsonb_set(doc, '{rows}', coalesce(p_rows, '[]'::jsonb)),
         version = version + 1
   where event_id = p_event_id;
  if not found then
    raise exception 'app_queue_put: queue % is not locked/created', p_event_id;
  end if;
end $$;

-- JSON null and a missing key alike → SQL NULL.
create or replace function app_nullable(p_value jsonb) returns jsonb
language sql immutable as $$
  select case when p_value is null or jsonb_typeof(p_value) = 'null' then null else p_value end
$$;

-- Is the event open for check-in at p_now? Mirror of services/events.ts
-- effectiveStatus: an active event closes at date.end, or without one at the
-- end of its start's KST day.
create or replace function app_event_open(p_event jsonb, p_now timestamptz)
returns boolean language sql stable as $$
  select p_event ->> 'status' = 'active'
     and coalesce(
           (app_nullable(p_event -> 'date' -> 'end') #>> '{}')::timestamptz,
           (date_trunc('day', ((p_event -> 'date' ->> 'start')::timestamptz at time zone 'UTC')
                              + interval '9 hours')
            + interval '1 day' - interval '9 hours') at time zone 'UTC'
         ) >= p_now
$$;

-- ---------------------------------------------------------------------------
-- 1b. Seminar rules (mirrors of services/seminars.ts and core/semester.ts —
--     keep them in step)
-- ---------------------------------------------------------------------------

-- The regular term an instant falls in, by the KST calendar: Mar–Aug → YY-1,
-- Sep–Feb → YY-2 (Jan/Feb belong to the previous year's second term).
create or replace function app_term_of(p_at text) returns text
language sql stable as $$
  select case
    when extract(month from k) between 3 and 8
      then lpad((extract(year from k)::int % 100)::text, 2, '0') || '-1'
    else lpad(((extract(year from k)::int
                - case when extract(month from k) >= 9 then 0 else 1 end) % 100)::text,
              2, '0') || '-2'
  end
  from (select (p_at::timestamptz at time zone 'UTC') + interval '9 hours' as k) as t
$$;

-- May the term be re-derived from the schedule? Not when an admin pinned it,
-- nor for a vacation term (YY-S / YY-W), which derivation cannot express.
create or replace function app_may_derive_semester(p_sem jsonb) returns boolean
language sql immutable as $$
  select not coalesce((p_sem ->> 'semesterPinned')::boolean, false)
     and coalesce(p_sem ->> 'semester', '') !~ '^\d{2}-[SW]$'
$$;

-- Rows written before publicationStatus existed are published.
create or replace function app_seminar_status(p_sem jsonb) returns text
language sql immutable as $$
  select coalesce(p_sem ->> 'publicationStatus', 'published')
$$;

-- Events that belong to a seminar: anchored to it ('seminar:<id>'), or —
-- for migrated rows without an anchor — hanging off its activity.
create or replace function app_is_seminar_event(p_event jsonb, p_sem jsonb)
returns boolean language sql immutable as $$
  select p_event ->> 'sourceRequestId' = 'seminar:' || (p_sem ->> 'id')
      or (p_sem ->> 'activityId' is not null
          and p_event ->> 'activityId' = p_sem ->> 'activityId')
$$;

-- ---------------------------------------------------------------------------
-- 2. Flows
-- ---------------------------------------------------------------------------

-- Delete a seminar record (admin). A non-published (cancelled/unpublished)
-- seminar is what hides its activity (services/visibility.ts), so deleting it
-- also retires that activity with its sessions and queues — refused while
-- attendance evidence remains (credit beyond the presenters' automatic one,
-- or a pending/approved check-in) or while anything else hangs off the
-- activity (another seminar, a gallery entry, a study session). Its request
-- stays as history, marked closed (shown as 취소됨), unless another seminar
-- still stands on it. Returns the asset keys the caller may clean up.
--   p = { id }
create or replace function flow_delete_seminar(p jsonb) returns jsonb
language plpgsql set search_path = public as $$
declare
  v_id       text := p ->> 'id';
  v_seminars jsonb;
  v_sem      jsonb;
  v_hidden   boolean;
  v_act      text;
  v_events   jsonb;
  v_session  jsonb;
  v_sessions text[] := '{}';
  v_requests jsonb;
  v_request  jsonb;
  v_req_id   text;
  v_assets   jsonb;
  v_touched  text[] := array['seminars'];
begin
  perform app_lock(array['activities', 'events', 'gallery-dinner',
                         'seminar-requests', 'seminars']);
  v_seminars := app_rows('seminars');
  v_sem := app_find(v_seminars, v_id);
  if v_sem is null then raise exception 'NOT_FOUND'; end if;

  -- Rows written before publicationStatus existed are published (§ migration).
  v_hidden := coalesce(v_sem ->> 'publicationStatus', 'published') <> 'published';
  v_act := v_sem ->> 'activityId';
  v_assets := coalesce(v_sem -> 'materials', '[]') || coalesce(v_sem -> 'photos', '[]')
              || jsonb_build_array(coalesce(v_sem ->> 'posterKey', ''));

  if v_hidden and v_act is not null then
    v_events := app_rows('events');
    if exists (select 1 from jsonb_array_elements(v_seminars) s
                where s ->> 'id' <> v_id and s ->> 'activityId' = v_act)
       or exists (select 1 from jsonb_array_elements(app_rows('gallery-dinner')) g
                   where g ->> 'activityId' = v_act)
       or exists (select 1 from jsonb_array_elements(v_events) e
                   where e ->> 'activityId' = v_act and e ->> 'studyId' is not null)
    then
      raise exception 'CONFLICT';
    end if;
    -- credit beyond the presenters' own (stamped automatically at publication)
    if exists (
      select 1
        from jsonb_array_elements(app_rows('activities')) a,
             jsonb_array_elements_text(a -> 'attendeeIds') as who
       where a ->> 'id' = v_act
         and not (coalesce(v_sem -> 'presenterIds', '[]') ? who)
    ) then
      raise exception 'CONFLICT';
    end if;
    for v_session in
      select e from jsonb_array_elements(v_events) e where e ->> 'activityId' = v_act
    loop
      v_sessions := v_sessions || (v_session ->> 'id');
    end loop;
    perform app_queue_lock(v_sessions);
    if exists (
      select 1 from unnest(v_sessions) as sid,
                    jsonb_array_elements(app_queue_rows(sid)) q
       where q ->> 'status' <> 'rejected'
    ) then
      raise exception 'CONFLICT';
    end if;
    perform app_queue_delete(sid) from unnest(v_sessions) as sid;
    perform app_put('events', app_without(v_events, 'activityId', v_act));
    perform app_put('activities', app_without(app_rows('activities'), 'id', v_act));
    v_touched := v_touched || array['events', 'activities'];
  end if;

  perform app_put('seminars', app_without(v_seminars, 'id', v_id));

  v_req_id := v_sem ->> 'sourceRequestId';
  if v_hidden and v_req_id is not null
     and not exists (select 1 from jsonb_array_elements(v_seminars) s
                      where s ->> 'id' <> v_id and s ->> 'sourceRequestId' = v_req_id)
  then
    v_requests := app_rows('seminar-requests');
    v_request := app_find(v_requests, v_req_id);
    if v_request is not null then
      v_assets := v_assets || jsonb_build_array(coalesce(v_request ->> 'posterKey', ''));
      perform app_put('seminar-requests', app_replace(v_requests, v_req_id,
        v_request || jsonb_build_object('closedAs', 'deleted', 'posterKey', '')));
      v_touched := v_touched || array['seminar-requests'];
    end if;
  end if;

  return jsonb_build_object(
    'touched', to_jsonb(v_touched),
    'touchedQueues', to_jsonb(v_sessions),
    'assets', v_assets);
end $$;

-- Publish a scheduled seminar (admin): flip it to published (deriving its
-- term from the schedule), create its activity and attendance event if they
-- do not exist yet (anchored 'seminar:<id>', so a re-run converges), link the
-- activity, and claim the announcement (announcedAt) when none was sent. The
-- caller sends the announcement after the commit only when `claimed`, and
-- releases the claim if sending fails. Re-running on a published seminar
-- fills in whatever is missing.
--   p = { id, now, activityId, eventId, pathId, attendCode }
--       (ids/tokens for rows that may need creating; now = KST ISO)
create or replace function flow_publish_seminar(p jsonb) returns jsonb
language plpgsql set search_path = public as $$
declare
  v_id       text := p ->> 'id';
  v_anchor   text := 'seminar:' || (p ->> 'id');
  v_seminars jsonb;
  v_sem      jsonb;
  v_sched    jsonb;
  v_date     jsonb;
  v_acts     jsonb;
  v_act      jsonb;
  v_events   jsonb;
  v_event    jsonb;
  v_claimed  boolean := false;
  v_touched  text[] := array['seminars'];
begin
  perform app_lock(array['activities', 'events', 'seminars']);
  v_seminars := app_rows('seminars');
  v_sem := app_find(v_seminars, v_id);
  if v_sem is null then raise exception 'NOT_FOUND'; end if;
  v_sched := app_nullable(v_sem -> 'schedule');
  -- a legacy published row that lost its schedule cannot be published again
  if app_seminar_status(v_sem) not in ('scheduled', 'published') or v_sched is null then
    raise exception 'CONFLICT';
  end if;

  if app_seminar_status(v_sem) = 'scheduled' then
    v_sem := v_sem || jsonb_build_object(
      'publicationStatus', 'published',
      'semester', case when app_may_derive_semester(v_sem)
                       then app_term_of(v_sched ->> 'startsAt')
                       else v_sem ->> 'semester' end);
  end if;
  v_date := jsonb_build_object(
    'start', v_sched -> 'startsAt',
    'end', coalesce(v_sched -> 'endsAt', 'null'::jsonb));

  v_acts := app_rows('activities');
  select a into v_act from jsonb_array_elements(v_acts) a
   where a ->> 'sourceRequestId' = v_anchor limit 1;
  if v_act is null then
    -- presenters are participants of their own seminar
    v_act := jsonb_build_object(
      'id', p ->> 'activityId',
      'title', v_sem ->> 'title',
      'date', v_date,
      'type', '세미나',
      'attendeeIds', coalesce(v_sem -> 'presenterIds', '[]'::jsonb),
      'sourceRequestId', v_anchor);
    perform app_put('activities', v_acts || jsonb_build_array(v_act));
    v_touched := v_touched || array['activities'];
  end if;

  v_events := app_rows('events');
  select e into v_event from jsonb_array_elements(v_events) e
   where e ->> 'sourceRequestId' = v_anchor limit 1;
  if v_event is null then
    v_event := jsonb_build_object(
      'id', p ->> 'eventId',
      'title', v_sem ->> 'title',
      'date', v_date,
      'type', '세미나',
      'status', 'active',
      'pathId', p ->> 'pathId',
      'attendCode', p ->> 'attendCode',
      'activityId', v_act ->> 'id',
      'applicantIds', '[]'::jsonb,
      'presenterIds', coalesce(v_sem -> 'presenterIds', '[]'::jsonb),
      'studyId', null,
      'sessionNo', null,
      'autoGenerated', false,
      'sourceRequestId', v_anchor);
    perform app_put('events', v_events || jsonb_build_array(v_event));
    v_touched := v_touched || array['events'];
  end if;

  v_sem := v_sem || jsonb_build_object('activityId', v_act ->> 'id');
  if v_sem ->> 'announcedAt' is null then
    v_sem := v_sem || jsonb_build_object('announcedAt', p ->> 'now');
    v_claimed := true;
  end if;
  perform app_put('seminars', app_replace(v_seminars, v_id, v_sem));

  return jsonb_build_object(
    'touched', to_jsonb(v_touched),
    'seminar', v_sem,
    'activityId', v_act ->> 'id',
    'eventId', v_event ->> 'id',
    'claimed', v_claimed);
end $$;

-- Change a seminar's schedule (admin). Before publication only the seminar
-- row holds it; after, the same dates also live on its activity and
-- attendance event, and all three change together. A published seminar's
-- term follows the new date unless pinned. Also the way to give a legacy
-- published row (schedule lost in migration) its schedule back.
--   p = { id, schedule }  → { seminar, changed }
create or replace function flow_update_seminar_schedule(p jsonb) returns jsonb
language plpgsql set search_path = public as $$
declare
  v_id       text := p ->> 'id';
  v_new      jsonb := p -> 'schedule';
  v_seminars jsonb;
  v_sem      jsonb;
  v_old      jsonb;
  v_status   text;
  v_changed  boolean;
  v_date     jsonb;
  v_touched  text[] := array['seminars'];
begin
  perform app_lock(array['activities', 'events', 'seminars']);
  v_seminars := app_rows('seminars');
  v_sem := app_find(v_seminars, v_id);
  if v_sem is null then raise exception 'NOT_FOUND'; end if;
  v_status := app_seminar_status(v_sem);
  if v_status in ('cancelled', 'unscheduled') then raise exception 'CONFLICT'; end if;

  v_old := app_nullable(v_sem -> 'schedule');
  v_changed := v_old is null
    or v_old ->> 'startsAt' is distinct from v_new ->> 'startsAt'
    or v_old ->> 'endsAt' is distinct from v_new ->> 'endsAt'
    or v_old ->> 'location' is distinct from v_new ->> 'location';
  v_sem := v_sem || jsonb_build_object(
    'schedule', v_new,
    'semester', case when v_status = 'published' and app_may_derive_semester(v_sem)
                     then app_term_of(v_new ->> 'startsAt')
                     else v_sem ->> 'semester' end);
  perform app_put('seminars', app_replace(v_seminars, v_id, v_sem));

  if v_status = 'published' then
    v_date := jsonb_build_object(
      'start', v_new -> 'startsAt',
      'end', coalesce(v_new -> 'endsAt', 'null'::jsonb));
    perform app_put('activities', (
      select coalesce(jsonb_agg(
               case when a ->> 'id' = v_sem ->> 'activityId'
                      or a ->> 'sourceRequestId' = 'seminar:' || v_id
                    then a || jsonb_build_object('date', v_date) else a end
               order by n), '[]'::jsonb)
        from jsonb_array_elements(app_rows('activities')) with ordinality as x(a, n)));
    perform app_put('events', (
      select coalesce(jsonb_agg(
               case when app_is_seminar_event(e, v_sem)
                    then e || jsonb_build_object('date', v_date) else e end
               order by n), '[]'::jsonb)
        from jsonb_array_elements(app_rows('events')) with ordinality as x(e, n)));
    v_touched := v_touched || array['activities', 'events'];
  end if;

  return jsonb_build_object(
    'touched', to_jsonb(v_touched),
    'seminar', v_sem,
    'changed', v_changed);
end $$;

-- Cancel a seminar and its attendance events (presenter or admin). A
-- presenter may cancel only their own seminar and only before it starts; an
-- admin may cancel a started one with `acknowledgeStarted`. Activities and
-- attendance are kept (the read side hides them). Idempotent. "Started" is
-- the schedule's start, or — for a legacy published row without one —
-- "already held".
--   p = { id, memberId, isAdmin, acknowledgeStarted, now }
--   → { seminar, flipped, wasAnnounced, started }
create or replace function flow_cancel_seminar(p jsonb) returns jsonb
language plpgsql set search_path = public as $$
declare
  v_id        text := p ->> 'id';
  v_is_admin  boolean := coalesce((p ->> 'isAdmin')::boolean, false);
  v_seminars  jsonb;
  v_sem       jsonb;
  v_sched     jsonb;
  v_status    text;
  v_started   boolean;
  v_flipped   boolean := false;
  v_announced boolean := false;
  v_events    jsonb;
  v_next      jsonb;
  v_touched   text[] := '{}';
begin
  perform app_lock(array['events', 'seminars']);
  v_seminars := app_rows('seminars');
  v_sem := app_find(v_seminars, v_id);
  if v_sem is null then raise exception 'NOT_FOUND'; end if;
  v_status := app_seminar_status(v_sem);
  v_sched := app_nullable(v_sem -> 'schedule');
  v_started := case when v_sched is not null
                    then (v_sched ->> 'startsAt')::timestamptz <= (p ->> 'now')::timestamptz
                    else v_status = 'published' end;

  if not v_is_admin then
    if not (coalesce(v_sem -> 'presenterIds', '[]'::jsonb) ? (p ->> 'memberId'))
       or v_started then
      raise exception 'FORBIDDEN';
    end if;
  elsif v_started and not coalesce((p ->> 'acknowledgeStarted')::boolean, false) then
    raise exception 'CONFLICT';
  end if;

  if v_status <> 'cancelled' then
    v_announced := v_status = 'published' and v_sem ->> 'announcedAt' is not null;
    v_sem := v_sem || jsonb_build_object('publicationStatus', 'cancelled');
    perform app_put('seminars', app_replace(v_seminars, v_id, v_sem));
    v_touched := v_touched || array['seminars'];
    v_flipped := true;
  end if;

  v_events := app_rows('events');
  select coalesce(jsonb_agg(
           case when app_is_seminar_event(e, v_sem) and e ->> 'status' <> 'cancelled'
                then e || jsonb_build_object('status', 'cancelled') else e end
           order by n), '[]'::jsonb)
    into v_next
    from jsonb_array_elements(v_events) with ordinality as x(e, n);
  if v_next <> v_events then
    perform app_put('events', v_next);
    v_touched := v_touched || array['events'];
  end if;

  return jsonb_build_object(
    'touched', to_jsonb(v_touched),
    'seminar', v_sem,
    'flipped', v_flipped,
    'wasAnnounced', v_announced,
    'started', v_started);
end $$;

-- Check in to an event (member): a pending row in the event's queue. The
-- event is read under a SHARE lock — check-ins do not wait for each other,
-- but a delete or cancel of the event cannot commit in between, so no row is
-- ever queued for an event that is gone or closed.
--   p = { eventId, memberId, id, now }  (id = new row id, now = KST ISO)
create or replace function flow_check_in(p jsonb) returns jsonb
language plpgsql set search_path = public as $$
declare
  v_event_id text := p ->> 'eventId';
  v_member   text := p ->> 'memberId';
  v_event    jsonb;
  v_rows     jsonb;
  v_record   jsonb;
begin
  perform 1 from app_tables where name = 'events' for share;
  v_event := app_find(app_rows('events'), v_event_id);
  if v_event is null then raise exception 'NOT_FOUND'; end if;
  if not app_event_open(v_event, (p ->> 'now')::timestamptz) then
    raise exception 'EVENT_NOT_OPEN';
  end if;

  insert into app_queues (event_id, version, doc)
    values (v_event_id, 1, jsonb_build_object('schemaVersion', 1, 'rows', '[]'::jsonb))
    on conflict (event_id) do nothing;
  perform app_queue_lock(array[v_event_id]);
  v_rows := app_queue_rows(v_event_id);
  if exists (select 1 from jsonb_array_elements(v_rows) r where r ->> 'memberId' = v_member) then
    raise exception 'CONFLICT';
  end if;
  -- one-click completion records both instants
  v_record := jsonb_build_object(
    'id', p ->> 'id',
    'memberId', v_member,
    'eventId', v_event_id,
    'startTime', p ->> 'now',
    'endTime', p ->> 'now',
    'status', 'pending');
  perform app_queue_put(v_event_id, v_rows || jsonb_build_array(v_record));

  return jsonb_build_object(
    'touchedQueues', jsonb_build_array(v_event_id),
    'record', v_record);
end $$;

-- Decide a check-in (admin): approve credits the member on the event's
-- activity; reject or delete of an APPROVED row takes that credit back
-- (API-SPEC §7-2). Queue row and activity change together, so an approve and
-- a reject racing on one row cannot leave a rejected row with credit.
--   p = { eventId, queueId, decision: 'approve' | 'reject' | 'delete' }
create or replace function flow_decide_attendance(p jsonb) returns jsonb
language plpgsql set search_path = public as $$
declare
  v_event_id text := p ->> 'eventId';
  v_queue_id text := p ->> 'queueId';
  v_decision text := p ->> 'decision';
  v_rows     jsonb;
  v_row      jsonb;
  v_member   text;
  v_event    jsonb;
  v_acts     jsonb;
  v_act      jsonb;
  v_touched  text[] := '{}';
begin
  if v_decision not in ('approve', 'reject', 'delete') then
    raise exception 'VALIDATION_FAILED';
  end if;
  perform app_lock(array['activities', 'events']);
  perform app_queue_lock(array[v_event_id]);
  v_rows := app_queue_rows(v_event_id);
  v_row := app_find(v_rows, v_queue_id);
  if v_row is null then raise exception 'NOT_FOUND'; end if;
  v_member := v_row ->> 'memberId';
  v_event := app_find(app_rows('events'), v_event_id);
  v_acts := app_rows('activities');

  if v_decision = 'approve' then
    if v_event is null then raise exception 'NOT_FOUND'; end if;
    v_act := app_find(v_acts, v_event ->> 'activityId');
    if v_act is null then raise exception 'NOT_FOUND'; end if; -- dangling reference
    if not (v_act -> 'attendeeIds' ? v_member) then
      perform app_put('activities', app_replace(v_acts, v_act ->> 'id',
        jsonb_set(v_act, '{attendeeIds}', (v_act -> 'attendeeIds') || to_jsonb(v_member))));
      v_touched := v_touched || array['activities'];
    end if;
    perform app_queue_put(v_event_id, app_replace(v_rows, v_queue_id,
      v_row || jsonb_build_object('status', 'approved')));
  else
    if v_row ->> 'status' = 'approved' and v_event is not null then
      v_act := app_find(v_acts, v_event ->> 'activityId');
      if v_act is not null and v_act -> 'attendeeIds' ? v_member then
        perform app_put('activities', app_replace(v_acts, v_act ->> 'id',
          jsonb_set(v_act, '{attendeeIds}', (v_act -> 'attendeeIds') - v_member)));
        v_touched := v_touched || array['activities'];
      end if;
    end if;
    if v_decision = 'reject' then
      perform app_queue_put(v_event_id, app_replace(v_rows, v_queue_id,
        v_row || jsonb_build_object('status', 'rejected')));
    else
      perform app_queue_put(v_event_id, app_without(v_rows, 'id', v_queue_id));
    end if;
  end if;

  return jsonb_build_object(
    'touched', to_jsonb(v_touched),
    'touchedQueues', jsonb_build_array(v_event_id));
end $$;

-- Delete an event (admin) with its queue — refused while check-ins are still
-- pending (API-SPEC §7-2). The event lock keeps a check-in from landing
-- between the pending test and the delete.
--   p = { id }
create or replace function flow_delete_event(p jsonb) returns jsonb
language plpgsql set search_path = public as $$
declare
  v_id     text := p ->> 'id';
  v_events jsonb;
begin
  perform app_lock(array['events']);
  perform app_queue_lock(array[v_id]);
  if exists (select 1 from jsonb_array_elements(app_queue_rows(v_id)) q
              where q ->> 'status' = 'pending') then
    raise exception 'CONFLICT';
  end if;
  v_events := app_rows('events');
  if app_find(v_events, v_id) is null then raise exception 'NOT_FOUND'; end if;
  perform app_put('events', app_without(v_events, 'id', v_id));
  perform app_queue_delete(v_id);
  return jsonb_build_object(
    'touched', jsonb_build_array('events'),
    'touchedQueues', jsonb_build_array(v_id));
end $$;

-- ---------------------------------------------------------------------------
-- 99. Privileges — flows and helpers run for the service role only.
--     (Guarded: PGlite has no Supabase roles.)
-- ---------------------------------------------------------------------------

do $$
declare
  f record;
  has_roles boolean := exists (select 1 from pg_roles where rolname = 'service_role');
begin
  for f in
    select p.oid::regprocedure as sig
      from pg_proc p join pg_namespace n on n.oid = p.pronamespace
     where n.nspname = 'public'
       and (p.proname like 'app\_%' or p.proname like 'flow\_%')
  loop
    execute format('revoke all on function %s from public', f.sig);
    if has_roles then
      execute format('revoke all on function %s from anon, authenticated', f.sig);
      execute format('grant execute on function %s to service_role', f.sig);
    end if;
  end loop;
end $$;
