import { z } from "zod";
import { ActivityType, DateRange, Id, SourceRequestId } from "./common";

// "cancelled" is terminal — unlike "expired" it can never be re-activated (ADM-04).
export const EventStatus = z.enum(["draft", "active", "expired", "cancelled"]);
export type EventStatus = z.infer<typeof EventStatus>;

export const EventSchema = z.object({
  id: Id,
  title: z.string().min(1),
  date: DateRange,
  type: ActivityType,
  status: EventStatus,
  pathId: z.string().min(1),
  attendCode: z.string().min(1),
  activityId: Id, // required — every session has an activity to record into
  applicantIds: z.array(Id),
  presenterIds: z.array(Id),
  studyId: Id.nullable(),
  sessionNo: z.number().int().positive().nullable(),
  autoGenerated: z.boolean(),
  sourceRequestId: SourceRequestId,
});

export type Event = z.infer<typeof EventSchema>;
